//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnulLine
    {
        public int Id { get; set; }
        public int HeadId { get; set; }
        public int LineNumber { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public double Count { get; set; }
        public double Discount { get; set; }
        public double VatAmount { get; set; }
        public int VatType { get; set; }
        public string BarCode { get; set; }
        public double PackCount { get; set; }
        public double RealPrice { get; set; }
        public int PriceOption { get; set; }
    
        public virtual AnnulHead AnnulHead { get; set; }
    }
}
