//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aparatai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aparatai()
        {
            this.CashierLogs = new HashSet<CashierLog>();
        }
    
        public int AparatoID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> NetworkNr { get; set; }
        public string AparatoPavadinimas { get; set; }
        public Nullable<int> AparatoNr { get; set; }
        public Nullable<short> SocketNr { get; set; }
        public Nullable<int> MyID { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> NonUVSNumber { get; set; }
        public Nullable<short> KasaType { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> Dep { get; set; }
        public string IPAdress { get; set; }
        public string Version { get; set; }
        public string FBVersion { get; set; }
        public Nullable<int> POSNr { get; set; }
        public string CPUName { get; set; }
        public Nullable<int> CPUFreq { get; set; }
        public string HardDriveModel { get; set; }
        public string HardDriveSerial { get; set; }
        public Nullable<double> HardDriveSize_Mb { get; set; }
        public string VideoName { get; set; }
        public Nullable<int> VideoRAM_Kb { get; set; }
        public Nullable<int> RAM_Mb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashierLog> CashierLogs { get; set; }
    }
}
