//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ataskaito
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Nuo { get; set; }
        public Nullable<System.DateTime> Iki { get; set; }
        public Nullable<int> NuoZ { get; set; }
        public Nullable<int> IkiZ { get; set; }
        public Nullable<int> Aparatas { get; set; }
        public bool Visi { get; set; }
        public Nullable<int> NuoKvito { get; set; }
        public Nullable<int> IkiKvito { get; set; }
        public Nullable<int> PeriodoTipas { get; set; }
        public Nullable<int> Detalumas { get; set; }
        public bool VisosGrupes { get; set; }
        public bool VisiTiekejai { get; set; }
        public Nullable<int> NuoKodo { get; set; }
        public Nullable<int> IkiKodo { get; set; }
        public bool RibotiPrekesKodus { get; set; }
        public bool VisiVazt { get; set; }
    }
}
