//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public short MinCharCount { get; set; }
        public short MaxCharCount { get; set; }
        public byte ValueFormat { get; set; }
        public string PossibleValues { get; set; }
        public bool IsRequired { get; set; }
        public bool IsPrintable { get; set; }
        public bool IsVisible { get; set; }
        public byte PrintFormat { get; set; }
        public byte Deleted { get; set; }
        public byte[] Timestamp { get; set; }
        public int Order { get; set; }
    }
}
