//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompPLU
    {
        public int ID { get; set; }
        public int Dep { get; set; }
        public int MainCode { get; set; }
        public string SupCode { get; set; }
        public double Coef { get; set; }
        public int SupType { get; set; }
    }
}
