//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponActivate
    {
        public int Id { get; set; }
        public int POSId { get; set; }
        public int idOnPos { get; set; }
        public System.DateTime DateTime { get; set; }
        public string CouponNumber { get; set; }
        public Nullable<int> ReceiptNr { get; set; }
        public decimal Balance { get; set; }
        public int CashierId { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
