//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetKorteleByID
    {
        public string Id_number { get; set; }
        public Nullable<short> CardType { get; set; }
        public Nullable<int> Statusas { get; set; }
        public string Key1B { get; set; }
        public string PusePIN { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
        public int ID { get; set; }
    }
}
