//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsDep
    {
        public int ID { get; set; }
        public string PLUGroup { get; set; }
        public string Dep { get; set; }
        public string Pav { get; set; }
        public bool DoNotSendToScales { get; set; }
    }
}
