//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inkasac
    {
        public int Id { get; set; }
        public int IdOnPos { get; set; }
        public int POSId { get; set; }
        public System.DateTime OpTime { get; set; }
        public double amount { get; set; }
        public int OpType { get; set; }
        public int ZNr { get; set; }
        public int CashierId { get; set; }
        public string OpName { get; set; }
        public string ObjId { get; set; }
        public string ObjName { get; set; }
    }
}
