//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kortele
    {
        public string Id_number { get; set; }
        public Nullable<short> CardType { get; set; }
        public Nullable<short> CardSubType { get; set; }
        public string Benzinas { get; set; }
        public Nullable<double> Bendras_limitas { get; set; }
        public Nullable<double> Limitas_dienai { get; set; }
        public Nullable<double> Limitas_menesiui { get; set; }
        public int Savininkas { get; set; }
        public Nullable<int> Naudotojas { get; set; }
        public Nullable<double> Kiekis { get; set; }
        public Nullable<double> PrevKiekis { get; set; }
        public Nullable<int> Statusas { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public bool PasiustaICardlista { get; set; }
        public string Key1B { get; set; }
        public string PusePIN { get; set; }
        public Nullable<double> MenesioLikutis { get; set; }
        public Nullable<int> Menuo { get; set; }
        public Nullable<short> BlokavimoPriezastis { get; set; }
        public Nullable<double> PrevMenesioLikutis { get; set; }
        public bool SektiMenesioLimita { get; set; }
        public bool SektiBendraLimita { get; set; }
        public bool MK_MagneticCard { get; set; }
        public bool MK_JudintaDabar { get; set; }
        public Nullable<System.DateTime> Redaguota { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
        public int ID { get; set; }
        public string GroupId { get; set; }
    }
}
