//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KupList
    {
        public int ID { get; set; }
        public Nullable<int> AparatoID { get; set; }
        public Nullable<int> Kasininkas { get; set; }
        public Nullable<int> KvitoNr { get; set; }
        public Nullable<System.DateTime> Laikas { get; set; }
        public Nullable<double> Suma { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public string Kuponas { get; set; }
        public Nullable<int> Kiekis { get; set; }
        public Nullable<int> Tipas { get; set; }
    }
}
