//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvitaiJoin
    {
        public int KvGID { get; set; }
        public int KvEID { get; set; }
        public int AparatoID { get; set; }
        public int KvitoNr { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<byte> Day { get; set; }
        public Nullable<byte> Hour { get; set; }
        public Nullable<byte> Minute { get; set; }
        public Nullable<byte> ApmokejimoRusis { get; set; }
        public Nullable<double> Suma { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public Nullable<double> Antkainis { get; set; }
        public Nullable<double> Mokesciai { get; set; }
        public string KortelesNr { get; set; }
        public Nullable<int> Kasininkas { get; set; }
        public Nullable<int> Znr { get; set; }
        public Nullable<int> PrekesKodas { get; set; }
        public Nullable<double> Kiekis { get; set; }
        public Nullable<double> Expr1 { get; set; }
    }
}
