//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvitoGalva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KvitoGalva()
        {
            this.AgeVerifications = new HashSet<AgeVerification>();
            this.ClientInfoes = new HashSet<ClientInfo>();
            this.KvitoEilutes = new HashSet<KvitoEilute>();
            this.Rewards = new HashSet<Reward>();
            this.Points_Headers = new HashSet<Points_Headers>();
            this.Payments = new HashSet<Payment>();
            this.SellDiscounts = new HashSet<SellDiscount>();
            this.SellEntries = new HashSet<SellEntry>();
        }
    
        public int ID { get; set; }
        public int AparatoID { get; set; }
        public int KvitoNr { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<byte> Day { get; set; }
        public Nullable<byte> Hour { get; set; }
        public Nullable<byte> Minute { get; set; }
        public Nullable<byte> ApmokejimoRusis { get; set; }
        public Nullable<double> Suma { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public Nullable<double> Antkainis { get; set; }
        public Nullable<double> Mokesciai { get; set; }
        public string KortelesNr { get; set; }
        public Nullable<int> Kasininkas { get; set; }
        public Nullable<int> Znr { get; set; }
        public Nullable<int> GalvosID { get; set; }
        public string KvitoNr2 { get; set; }
        public string NlKort { get; set; }
        public Nullable<double> SumaGryni { get; set; }
        public Nullable<short> Seconds { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> DurationToPushTotal { get; set; }
        public Nullable<int> Flags { get; set; }
        public string InvNr { get; set; }
        public string InvNr_Parent { get; set; }
        public Nullable<int> ReturnReason { get; set; }
        public Nullable<int> PosOrGroupId_Parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgeVerification> AgeVerifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientInfo> ClientInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KvitoEilute> KvitoEilutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reward> Rewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Points_Headers> Points_Headers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellDiscount> SellDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellEntry> SellEntries { get; set; }
    }
}
