//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvitoEilute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KvitoEilute()
        {
            this.InactivityTimes = new HashSet<InactivityTime>();
            this.Price_Discounts_Items = new HashSet<Price_Discounts_Items>();
            this.Points_Items = new HashSet<Points_Items>();
        }
    
        public int ID { get; set; }
        public int GalvosID { get; set; }
        public Nullable<int> PrekesKodas { get; set; }
        public Nullable<double> Kiekis { get; set; }
        public Nullable<double> Kaina { get; set; }
        public Nullable<double> Suma { get; set; }
        public Nullable<double> Mokesciai { get; set; }
        public Nullable<double> Nuolaida { get; set; }
        public Nullable<int> PrekesID { get; set; }
        public string Barkodas { get; set; }
        public Nullable<double> VietDez { get; set; }
        public Nullable<double> Savikaina { get; set; }
        public Nullable<double> RealKaina { get; set; }
        public Nullable<int> PriceOption { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<int> SellFlags { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<short> PriceType { get; set; }
        public string PriceOriginType { get; set; }
        public Nullable<long> PriceIdentificator { get; set; }
        public string PackerID { get; set; }
        public Nullable<double> MPValueGranted { get; set; }
        public Nullable<double> MPValuePaid { get; set; }
        public string StrCode { get; set; }
        public Nullable<int> ParentLineNo { get; set; }
        public Nullable<int> OriginalLineNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InactivityTime> InactivityTimes { get; set; }
        public virtual KvitoGalva KvitoGalva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Discounts_Items> Price_Discounts_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Points_Items> Points_Items { get; set; }
    }
}
