//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastCheck
    {
        public int AparatoID { get; set; }
        public string AparatoPavadinimas { get; set; }
        public Nullable<int> MaxKv { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<byte> Day { get; set; }
        public Nullable<byte> Hour { get; set; }
        public Nullable<byte> Minute { get; set; }
    }
}
