//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatavimoVienetai
    {
        public byte MatoKodas { get; set; }
        public string MatoPavad { get; set; }
        public Nullable<short> MatoTikslumas { get; set; }
        public string Komentaras { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
        public int MatoID { get; set; }
        public byte Aktyvi { get; set; }
        public byte[] Delete { get; set; }
        public byte[] C_Delete { get; set; }
        public Nullable<bool> Weighable { get; set; }
    }
}
