//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaujienosSvarstyklem
    {
        public int ID { get; set; }
        public Nullable<int> PrekK { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> PrekesEilNr { get; set; }
        public string PrekesPav { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ScGroup { get; set; }
        public Nullable<System.DateTime> Laikas { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public string Sudetis { get; set; }
        public string TechSalygos { get; set; }
        public string LaikymoSalygos { get; set; }
        public Nullable<int> RealizValand { get; set; }
        public string PLUGroup { get; set; }
        public Nullable<int> Remove { get; set; }
        public string Gamintojas { get; set; }
        public string EnergetineVerte { get; set; }
        public string Ypatybes { get; set; }
        public string Aprasas2 { get; set; }
        public bool Weight { get; set; }
        public Nullable<double> GraduatedPrice { get; set; }
        public Nullable<double> GraduatePoint { get; set; }
        public Nullable<double> Price2 { get; set; }
        public Nullable<int> Group2 { get; set; }
        public Nullable<int> Group3 { get; set; }
        public string Sudetis2 { get; set; }
    }
}
