//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int ID { get; set; }
        public Nullable<int> LastKvitaiCounter { get; set; }
        public Nullable<int> LastPrekesCounter { get; set; }
        public Nullable<int> LastGrupesCounter { get; set; }
        public Nullable<int> LastVaztarasciaiCounter { get; set; }
        public string FirmosPavadinimas { get; set; }
        public Nullable<int> DallasPort { get; set; }
        public Nullable<int> ScotPort { get; set; }
        public Nullable<int> ScotMotherPort { get; set; }
        public Nullable<int> ScotBatchPort { get; set; }
        public Nullable<int> EmitentoKodas { get; set; }
        public Nullable<int> DefaultStatus { get; set; }
        public Nullable<double> PVM { get; set; }
        public Nullable<int> OrganizacijosID { get; set; }
        public string ExternalDB { get; set; }
        public Nullable<int> LastTimeDelta { get; set; }
        public bool AutoGroupSend { get; set; }
        public Nullable<int> LastECRCounter { get; set; }
        public string VaztExportDir { get; set; }
        public Nullable<int> DegalinesID { get; set; }
        public bool VaztAutoPrint { get; set; }
        public bool VaztAutoSend { get; set; }
        public string ExportNewCardsPath { get; set; }
        public Nullable<int> SendBarcodesToCenter { get; set; }
        public Nullable<int> LastBarCodeExportCounter { get; set; }
        public Nullable<System.DateTime> LastLogExportDate { get; set; }
        public string AutoVaztTiekejoID { get; set; }
        public Nullable<double> MinCash { get; set; }
        public bool GenSavikaina { get; set; }
        public Nullable<int> LastKvitoIDForSavikaina { get; set; }
        public bool KorKurLik { get; set; }
        public Nullable<int> LastKAVCounter { get; set; }
        public string FakturaFooter { get; set; }
        public string FakturaHeader { get; set; }
        public bool AllowFuelGroupEditions { get; set; }
        public bool AllowNonZeroQDeletions { get; set; }
        public bool KorVaztModeZ { get; set; }
        public Nullable<int> LastVaztExpID { get; set; }
        public bool LeistiSavikainaNeigiamiems { get; set; }
        public Nullable<int> LastVaztSarExportCounter { get; set; }
    }
}
