//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentBanks = new HashSet<PaymentBank>();
        }
    
        public int id { get; set; }
        public int GalvosId { get; set; }
        public int Type { get; set; }
        public double Amount { get; set; }
        public string CardNo { get; set; }
        public string AuthCode { get; set; }
        public Nullable<int> AuthModule { get; set; }
        public Nullable<double> CurrencyRate { get; set; }
        public Nullable<double> CurrencyAmount { get; set; }
    
        public virtual KvitoGalva KvitoGalva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBank> PaymentBanks { get; set; }
    }
}
