//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBank
    {
        public int id { get; set; }
        public int PaymentId { get; set; }
        public Nullable<short> BankId { get; set; }
        public Nullable<short> BankOwnerId { get; set; }
        public Nullable<bool> IsCobrand { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string AuthId { get; set; }
        public string Ci { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
