//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluAttributeAssigment
    {
        public int PluCode { get; set; }
        public string AttributeId { get; set; }
        public byte Deleted { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
