//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLUPicture
    {
        public int id { get; set; }
        public int dep { get; set; }
        public int plu { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public Nullable<int> picture_id { get; set; }
        public Nullable<int> picture_source_id { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string category_title { get; set; }
        public Nullable<int> Active { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
    }
}
