//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLUSetLine
    {
        public int ID { get; set; }
        public int dep { get; set; }
        public int setno { get; set; }
        public string BARCODE { get; set; }
        public double qty { get; set; }
        public double price { get; set; }
        public double tax { get; set; }
        public double packcount { get; set; }
        public Nullable<byte> PriceMode { get; set; }
    }
}
