//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLUSet
    {
        public int ID { get; set; }
        public int dep { get; set; }
        public int setNo { get; set; }
        public string barcode { get; set; }
        public int pricemode { get; set; }
        public string paytype { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public int reservation { get; set; }
        public int pickuplace { get; set; }
        public string customer { get; set; }
        public int KGID { get; set; }
    }
}
