//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrekesIstorija
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Laikas { get; set; }
        public Nullable<int> PrekesKodas { get; set; }
        public Nullable<int> PrekesID { get; set; }
        public Nullable<int> Operacija { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<short> Tipas { get; set; }
        public Nullable<int> SubOperacija { get; set; }
    }
}
