//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prekes2
    {
        public int id { get; set; }
        public int PrekesId { get; set; }
        public Nullable<double> Price5 { get; set; }
        public Nullable<double> Price6 { get; set; }
        public Nullable<double> Price7 { get; set; }
        public string ManufacId { get; set; }
        public string ItemGroupId { get; set; }
        public string BrandId { get; set; }
        public Nullable<int> Flags { get; set; }
        public string PriceOriginType { get; set; }
        public Nullable<long> PriceIdentificator { get; set; }
    }
}
