//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preke
    {
        public string PrekesPavadinimas { get; set; }
        public string PrekesKomentaras { get; set; }
        public double PrekesKaina { get; set; }
        public Nullable<byte> PrekesMatas { get; set; }
        public double PrekesKiekis { get; set; }
        public int PrekesKodas { get; set; }
        public int GrupesID { get; set; }
        public bool Aktyvi { get; set; }
        public byte[] Aparatai { get; set; }
        public Nullable<System.DateTime> Laikas { get; set; }
        public Nullable<int> GlobalID { get; set; }
        public int ID { get; set; }
        public byte[] C_Aparatai { get; set; }
        public byte[] AparataiL { get; set; }
        public byte[] C_AparataiL { get; set; }
        public byte[] Delete { get; set; }
        public byte[] C_Delete { get; set; }
        public Nullable<double> MinKiekis { get; set; }
        public Nullable<int> TiekejoID { get; set; }
        public Nullable<short> N_Type { get; set; }
        public Nullable<double> N_1_Nuo { get; set; }
        public Nullable<double> N_1_Kiek { get; set; }
        public Nullable<double> N_2_Nuo { get; set; }
        public Nullable<double> N_2_Kiek { get; set; }
        public Nullable<double> PrekesKaina2 { get; set; }
        public Nullable<double> DidmenineKaina { get; set; }
        public Nullable<double> DidmenineKaina2 { get; set; }
        public Nullable<int> Dep { get; set; }
        public Nullable<bool> Updating { get; set; }
        public short PriceType { get; set; }
        public int BlockType { get; set; }
    }
}
