//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellDiscount()
        {
            this.Price_Discounts_Items = new HashSet<Price_Discounts_Items>();
        }
    
        public int id { get; set; }
        public int GalvosId { get; set; }
        public int Type { get; set; }
        public Nullable<int> SubType { get; set; }
        public Nullable<int> CustNo { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<double> Amount { get; set; }
        public string CardNo { get; set; }
        public string DiscountTitle { get; set; }
    
        public virtual KvitoGalva KvitoGalva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Discounts_Items> Price_Discounts_Items { get; set; }
    }
}
