//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellEntry
    {
        public int id { get; set; }
        public int GalvosId { get; set; }
        public int SellLine { get; set; }
        public int EntryCode { get; set; }
        public string Entry { get; set; }
    
        public virtual KvitoGalva KvitoGalva { get; set; }
    }
}
