//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skaitliukai
    {
        public int ID { get; set; }
        public Nullable<int> AparatoID { get; set; }
        public Nullable<int> Zetas { get; set; }
        public string Pistoletas { get; set; }
        public Nullable<int> Benzinas { get; set; }
        public Nullable<double> Skaitliukas { get; set; }
        public Nullable<double> KiekisGryni { get; set; }
        public Nullable<double> KiekisKort { get; set; }
        public Nullable<double> KiekisTech { get; set; }
        public Nullable<double> KiekisOver { get; set; }
        public Nullable<int> IDZ { get; set; }
        public Nullable<short> PistNr { get; set; }
        public Nullable<short> TankNr { get; set; }
    }
}
