//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talpos
    {
        public Nullable<int> RezervuaroNr { get; set; }
        public Nullable<int> Kodas { get; set; }
        public Nullable<double> KompiuterioLikutis { get; set; }
        public Nullable<double> TalposDydis { get; set; }
        public Nullable<double> TurisNeperskaiciuotas { get; set; }
        public Nullable<double> TurisPerskaiciuotas { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Lygis { get; set; }
        public Nullable<double> VandensLygis { get; set; }
        public Nullable<System.DateTime> MatavimoLaikas { get; set; }
        public Nullable<bool> IsDevice { get; set; }
        public Nullable<int> PrekyvID { get; set; }
        public Nullable<int> Zetas { get; set; }
        public int ID { get; set; }
    }
}
