//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiekejai
    {
        public int ID { get; set; }
        public string Pavadinimas { get; set; }
        public Nullable<int> IsorinisKodas { get; set; }
        public Nullable<int> VidinisKodas { get; set; }
        public Nullable<int> Antkainis { get; set; }
        public Nullable<int> Nuolaida { get; set; }
        public string Telefonai { get; set; }
        public string PVMKodas { get; set; }
        public string ImKodas { get; set; }
        public string Adresas { get; set; }
        public Nullable<int> SaskaitosNr { get; set; }
        public string BankoKodas { get; set; }
    }
}
