//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStamp
    {
        public int id { get; set; }
        public string Module { get; set; }
        public int ApID { get; set; }
        public byte[] Value { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
