//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tomra_Barcodes
    {
        public int Id { get; set; }
        public string TerminalId { get; set; }
        public int STAN { get; set; }
        public string Barcode { get; set; }
        public string ReceiptNr { get; set; }
        public int status { get; set; }
        public string TomraReceiptId { get; set; }
    }
}
