//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateTax
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<byte> Mask { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
        public byte[] Delete { get; set; }
        public byte[] C_Delete { get; set; }
    }
}
