//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateFH
    {
        public int ID { get; set; }
        public bool FooterHeader { get; set; }
        public string Text { get; set; }
        public byte Line { get; set; }
        public Nullable<byte> Font { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public byte[] Aparatai { get; set; }
        public byte[] C_Aparatai { get; set; }
    }
}
