//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdatePLU
    {
        public int ID { get; set; }
        public Nullable<int> Dep { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public int Code { get; set; }
        public string BarCode { get; set; }
        public decimal Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<double> Tax1 { get; set; }
        public Nullable<double> Tax2 { get; set; }
        public Nullable<double> Tax3 { get; set; }
        public Nullable<double> Tax4 { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<byte> UnitScale { get; set; }
        public string GroupName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> GroupTax { get; set; }
        public Nullable<int> GroupCat { get; set; }
        public Nullable<double> GroupDiscount1qty { get; set; }
        public Nullable<double> GroupDiscount1amount { get; set; }
        public Nullable<double> GroupDiscount2qty { get; set; }
        public Nullable<double> GroupDiscount2amount { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<double> Discount1qty { get; set; }
        public Nullable<double> Discount1amount { get; set; }
        public Nullable<double> Discount2qty { get; set; }
        public Nullable<double> Discount2amount { get; set; }
        public Nullable<byte> ToScales { get; set; }
        public Nullable<byte> Weighting { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<int> Veiksmas { get; set; }
    }
}
