//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility
    {
        public int id { get; set; }
        public int Dep { get; set; }
        public int KasosNr { get; set; }
        public int Kasininkas { get; set; }
        public int GalvosID { get; set; }
        public int KvitoNr { get; set; }
        public double Suma { get; set; }
        public string ServiceBarcode { get; set; }
        public string GoodsBarcode { get; set; }
        public System.DateTime Laikas { get; set; }
        public Nullable<int> EilNr { get; set; }
    }
}
