//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaztarascioEilute
    {
        public int ID { get; set; }
        public Nullable<int> VaztarascioID { get; set; }
        public Nullable<int> PrekesKodas { get; set; }
        public Nullable<int> PrekesID { get; set; }
        public Nullable<double> Kiekis { get; set; }
        public Nullable<double> GavimoKaina { get; set; }
        public Nullable<int> GavimoForma { get; set; }
        public Nullable<double> PardavimoKaina { get; set; }
        public Nullable<double> GavimoSuma { get; set; }
    }
}
