//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaztarasciai
    {
        public int ID { get; set; }
        public string Numeris { get; set; }
        public Nullable<int> Tiekejas { get; set; }
        public System.DateTime Data { get; set; }
        public string Komentaras { get; set; }
        public bool Registruotas { get; set; }
        public Nullable<int> Zetas { get; set; }
        public Nullable<int> Vnr { get; set; }
        public Nullable<int> AparatoID { get; set; }
        public Nullable<System.DateTime> RegistracijosData { get; set; }
        public Nullable<int> Tipas { get; set; }
        public Nullable<double> SumaBeNuolaidos { get; set; }
        public Nullable<double> NuolaidosSuma { get; set; }
        public Nullable<double> NuolaidosProc { get; set; }
        public Nullable<double> GavimoPVM { get; set; }
        public Nullable<byte> Exported { get; set; }
    }
}
