//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zetai
    {
        public int ID { get; set; }
        public int Zetas { get; set; }
        public Nullable<System.DateTime> NUO { get; set; }
        public Nullable<System.DateTime> IKI { get; set; }
        public Nullable<System.DateTime> KADA { get; set; }
        public Nullable<double> Realizacijos_suma_gryni { get; set; }
        public Nullable<double> Grazinta_prekiu_gryni { get; set; }
        public Nullable<double> Suteikta_nuolaida_gryni { get; set; }
        public Nullable<double> Realizacijos_suma_korteles { get; set; }
        public Nullable<double> Grazinta_prekiu_korteles { get; set; }
        public Nullable<double> Suteikta_nuolaida_korteles { get; set; }
        public Nullable<double> BSapyvarta { get; set; }
        public Nullable<double> BSgrazinimai { get; set; }
        public Nullable<double> BSrealizacija { get; set; }
        public Nullable<double> SGapyvarta { get; set; }
        public Nullable<double> SGgrazinimai { get; set; }
        public Nullable<double> SGrealizacija { get; set; }
        public Nullable<double> SKapyvarta { get; set; }
        public Nullable<double> SKgrazinimai { get; set; }
        public Nullable<double> SKrealizacija { get; set; }
        public Nullable<int> KvitaiNuo { get; set; }
        public Nullable<int> KvitaiIki { get; set; }
        public Nullable<double> Kasa_pamainos_pradzioje { get; set; }
        public Nullable<double> Realizacija { get; set; }
        public Nullable<double> Inkasacija { get; set; }
        public Nullable<double> Kasa_pamainos_pabaigoje { get; set; }
        public string Pamaina_perdave { get; set; }
        public string Pamaina_prieme { get; set; }
        public Nullable<double> Kita_kort { get; set; }
        public Nullable<double> Kita_gryni { get; set; }
        public Nullable<double> Viso { get; set; }
        public int COUNT { get; set; }
        public Nullable<double> Neapmokestinta { get; set; }
        public Nullable<double> MokSuma1 { get; set; }
        public Nullable<double> Mok1 { get; set; }
        public Nullable<double> MokSuma2 { get; set; }
        public Nullable<double> Mok2 { get; set; }
        public Nullable<double> MokSuma3 { get; set; }
        public Nullable<double> Mok3 { get; set; }
        public Nullable<double> MokSuma4 { get; set; }
        public Nullable<double> Mok4 { get; set; }
        public Nullable<double> MokSuma5 { get; set; }
        public Nullable<double> Mok5 { get; set; }
    }
}
