using Filuet.ASC.Kiosk.OnBoard.Catalog.Abstractions.Services;
using Filuet.Utils.Common.Business;
using System;

namespace Filuet.ASC.Kiosk.OnBoard.Catalog.Service
{
    public class CatalogService : ICatalogService
    {
        public string GetName(string uid, Lang language)
        {
            // Stub of the hill
            if (string.Equals(uid, "0105", StringComparison.InvariantCultureIgnoreCase)) return "Tea Extracts - original flavor (50 g)";
            else if (string.Equals(uid, "0106", StringComparison.InvariantCultureIgnoreCase)) return "Tea Extracts - original flavor (100 g)";
            else if (string.Equals(uid, "0117", StringComparison.InvariantCultureIgnoreCase)) return "Yellow";
            else if (string.Equals(uid, "0124", StringComparison.InvariantCultureIgnoreCase)) return "N-R-G";
            else if (string.Equals(uid, "0139", StringComparison.InvariantCultureIgnoreCase)) return "Roseguard";
            else if (string.Equals(uid, "0143", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - strawberry";
            else if (string.Equals(uid, "0146", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - cookies and creme";
            else if (string.Equals(uid, "0155", StringComparison.InvariantCultureIgnoreCase)) return "Gourmet Tomato Soup";
            else if (string.Equals(uid, "0242", StringComparison.InvariantCultureIgnoreCase)) return "Formula 3 - PPP";
            else if (string.Equals(uid, "0257", StringComparison.InvariantCultureIgnoreCase)) return "Tea Extracts - peach flavor (50 g)";
            else if (string.Equals(uid, "0260", StringComparison.InvariantCultureIgnoreCase)) return "Protein bar - Lemon";
            else if (string.Equals(uid, "1065", StringComparison.InvariantCultureIgnoreCase)) return "Aloe Concentrate - mango flavor";
            else if (string.Equals(uid, "1800", StringComparison.InvariantCultureIgnoreCase)) return "F2 - for men, vitamin and mineral complex";
            else if (string.Equals(uid, "1819", StringComparison.InvariantCultureIgnoreCase)) return "F2 - for women, vitamin and mineral complex";
            else if (string.Equals(uid, "2669", StringComparison.InvariantCultureIgnoreCase)) return "Express Bar - chocolate";
            else if (string.Equals(uid, "2670", StringComparison.InvariantCultureIgnoreCase)) return "Express Bar - red berry";
            else if (string.Equals(uid, "2864", StringComparison.InvariantCultureIgnoreCase)) return "Oat Apple Fibre Drink";
            else if (string.Equals(uid, "3114", StringComparison.InvariantCultureIgnoreCase)) return "Fiber and Herb Tablets";
            else if (string.Equals(uid, "3143", StringComparison.InvariantCultureIgnoreCase)) return "Roasted Soy Beans";
            else if (string.Equals(uid, "3152", StringComparison.InvariantCultureIgnoreCase)) return "LIFTOFF® - Lemon-Lime";
            else if (string.Equals(uid, "5451", StringComparison.InvariantCultureIgnoreCase)) return "Mini Herbalife Member Pack (HMP)";
            else if (string.Equals(uid, "0003", StringComparison.InvariantCultureIgnoreCase)) return "Tang Kuei";
            else if (string.Equals(uid, "0006", StringComparison.InvariantCultureIgnoreCase)) return "Aloe Concentrate - original flavor";
            else if (string.Equals(uid, "0020", StringComparison.InvariantCultureIgnoreCase)) return "Xtra-Cal";
            else if (string.Equals(uid, "0043", StringComparison.InvariantCultureIgnoreCase)) return "Herbalifeline Max";
            else if (string.Equals(uid, "0050", StringComparison.InvariantCultureIgnoreCase)) return "Thermo Complete";
            else if (string.Equals(uid, "9909", StringComparison.InvariantCultureIgnoreCase)) return "Annual Processing Fee";
            else if (string.Equals(uid, "0909", StringComparison.InvariantCultureIgnoreCase)) return "Annual Supervisor Services Fee";
            else if (string.Equals(uid, "0141", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - vanilla";
            else if (string.Equals(uid, "0142", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - chocolate";
            else if (string.Equals(uid, "4464", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Spiced apple";
            else if (string.Equals(uid, "4462", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Banana Cream";
            else if (string.Equals(uid, "236A", StringComparison.InvariantCultureIgnoreCase)) return "3 Day trial Pack";
            else if (string.Equals(uid, "2561", StringComparison.InvariantCultureIgnoreCase)) return "Hand AND Body Wash";
            else if (string.Equals(uid, "2562", StringComparison.InvariantCultureIgnoreCase)) return "Soothing Gel";
            else if (string.Equals(uid, "2563", StringComparison.InvariantCultureIgnoreCase)) return "Everyday Hand AND Body Lotion";
            else if (string.Equals(uid, "2564", StringComparison.InvariantCultureIgnoreCase)) return "Strengthening Shampoo";
            else if (string.Equals(uid, "2565", StringComparison.InvariantCultureIgnoreCase)) return "Strengthening Conditioner";
            else if (string.Equals(uid, "2566", StringComparison.InvariantCultureIgnoreCase)) return "Bath and Body Bar";
            else if (string.Equals(uid, "0765", StringComparison.InvariantCultureIgnoreCase)) return "Soothing Aloe Cleanser";
            else if (string.Equals(uid, "0766", StringComparison.InvariantCultureIgnoreCase)) return "Polishing Citrus Cleanser";
            else if (string.Equals(uid, "0767", StringComparison.InvariantCultureIgnoreCase)) return "Energizing Herbal Toner";
            else if (string.Equals(uid, "0770", StringComparison.InvariantCultureIgnoreCase)) return "Firming Eye Gel";
            else if (string.Equals(uid, "0771", StringComparison.InvariantCultureIgnoreCase)) return "Hydrating Eye Cream";
            else if (string.Equals(uid, "0772", StringComparison.InvariantCultureIgnoreCase)) return "Instant Reveal Berry Scrub";
            else if (string.Equals(uid, "0773", StringComparison.InvariantCultureIgnoreCase)) return "Purifying Mint Clay Mask";
            else if (string.Equals(uid, "0827", StringComparison.InvariantCultureIgnoreCase)) return "Replenishing Night Cream";
            else if (string.Equals(uid, "0828", StringComparison.InvariantCultureIgnoreCase)) return "Protective Moisturizer SPF30";
            else if (string.Equals(uid, "003A", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Skin Headband - 1 ea";
            else if (string.Equals(uid, "0829", StringComparison.InvariantCultureIgnoreCase)) return "Line Minimizing Serum";
            else if (string.Equals(uid, "004A", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Skin Mirror - 1 ea";
            else if (string.Equals(uid, "0830", StringComparison.InvariantCultureIgnoreCase)) return "Daily Glow Moisturizer";
            else if (string.Equals(uid, "132A", StringComparison.InvariantCultureIgnoreCase)) return "HFF Herbalife Key ring - 1 ea";
            else if (string.Equals(uid, "0867", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Skin 7 day result kit";
            else if (string.Equals(uid, "180A", StringComparison.InvariantCultureIgnoreCase)) return "Water bottle HRBL NUT 900ml - 1 ea";
            else if (string.Equals(uid, "296A", StringComparison.InvariantCultureIgnoreCase)) return "HLN improved Shaker Cup - 5 ea";
            else if (string.Equals(uid, "297A", StringComparison.InvariantCultureIgnoreCase)) return "HLN Measuring Spoon - 10 ea";
            else if (string.Equals(uid, "302A", StringComparison.InvariantCultureIgnoreCase)) return "HLN small 2oz container - 10 ea";
            else if (string.Equals(uid, "305A", StringComparison.InvariantCultureIgnoreCase)) return "HLN Tablet Box - medium - 5 ea";
            else if (string.Equals(uid, "306A", StringComparison.InvariantCultureIgnoreCase)) return "HLN  Pen \"Comfy Grip\" - 10 ea";
            else if (string.Equals(uid, "309A", StringComparison.InvariantCultureIgnoreCase)) return "\"I love Herbalife\" Pin - 5 ea";
            else if (string.Equals(uid, "310A", StringComparison.InvariantCultureIgnoreCase)) return "\"I love Herbalife\" Green Pin - 5 ea";
            else if (string.Equals(uid, "311A", StringComparison.InvariantCultureIgnoreCase)) return "HLN Tape Measure  - 10 ea";
            else if (string.Equals(uid, "314A", StringComparison.InvariantCultureIgnoreCase)) return "HLN Tablet Crusher - 1 ea";
            else if (string.Equals(uid, "371A", StringComparison.InvariantCultureIgnoreCase)) return "HN 2L bottle - 1 ea";
            else if (string.Equals(uid, "7640", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Tote Bag - 1 ea";
            else if (string.Equals(uid, "8098", StringComparison.InvariantCultureIgnoreCase)) return "Senior Consultant button - 1 ea";
            else if (string.Equals(uid, "8573", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Aloe Bath Lily - 1 ea";
            else if (string.Equals(uid, "8697", StringComparison.InvariantCultureIgnoreCase)) return "Smart shaker - 1 ea";
            else if (string.Equals(uid, "8705", StringComparison.InvariantCultureIgnoreCase)) return "24H Smart shaker - 1 ea";
            else if (string.Equals(uid, "8710", StringComparison.InvariantCultureIgnoreCase)) return "24H Water bottle (750 ml) - 1 ea";
            else if (string.Equals(uid, "8711", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Nutrition sports bottle - small (500cc) - 1 ea";
            else if (string.Equals(uid, "299A", StringComparison.InvariantCultureIgnoreCase)) return "HLN Tablet Box - small - 10 ea";
            else if (string.Equals(uid, "8602", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Plastic Bags - large - 1 ea";
            else if (string.Equals(uid, "5001", StringComparison.InvariantCultureIgnoreCase)) return "Retail Order Form - 10 ea";
            else if (string.Equals(uid, "6240", StringComparison.InvariantCultureIgnoreCase)) return "Product Brochure (HEB)";
            else if (string.Equals(uid, "6241", StringComparison.InvariantCultureIgnoreCase)) return "Product Brochure (RUS)";
            else if (string.Equals(uid, "6473", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Breakfast Brochure (LG) - 10 ea";
            else if (string.Equals(uid, "6999", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Breakfast Brochure (RUS) - 10 ea";
            else if (string.Equals(uid, "7051", StringComparison.InvariantCultureIgnoreCase)) return "Shipper bag Herbalife - 1 ea";
            else if (string.Equals(uid, "5817", StringComparison.InvariantCultureIgnoreCase)) return "Invitation to Wellness Test (LG/RUS) - 50 ea";
            else if (string.Equals(uid, "9984", StringComparison.InvariantCultureIgnoreCase)) return "Wellness Test (LG) - 50 ea";
            else if (string.Equals(uid, "9985", StringComparison.InvariantCultureIgnoreCase)) return "Wellness Test (RUS) - 50 ea";
            else if (string.Equals(uid, "8669", StringComparison.InvariantCultureIgnoreCase)) return "Gift sertificate to Wellness Test - (LG)  - 3 ea";
            else if (string.Equals(uid, "9986", StringComparison.InvariantCultureIgnoreCase)) return "Gift sertificate to Wellness Test (RUS) - 3 ea";
            else if (string.Equals(uid, "5952", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Club invitation (LG/RUS) - 50 ea";
            else if (string.Equals(uid, "5411", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Club tickets (LG/RUS) - 50 ea";
            else if (string.Equals(uid, "5438", StringComparison.InvariantCultureIgnoreCase)) return "WLC handouts (LG) - 1 ea";
            else if (string.Equals(uid, "5443", StringComparison.InvariantCultureIgnoreCase)) return "WLC handouts  (RUS) - 1 ea";
            else if (string.Equals(uid, "N133", StringComparison.InvariantCultureIgnoreCase)) return "SKIN brochure (LG) - 5 ea";
            else if (string.Equals(uid, "N135", StringComparison.InvariantCultureIgnoreCase)) return "SKIN brochure (RUS) - 5 ea";
            else if (string.Equals(uid, "N322", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife SKIN gift certificate (LG) - 3 ea";
            else if (string.Equals(uid, "N321", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife SKIN gift certificate  (RUS) - 3 ea";
            else if (string.Equals(uid, "5652", StringComparison.InvariantCultureIgnoreCase)) return "Journal for NC (LG/RUS) - 1 ea";
            else if (string.Equals(uid, "N337", StringComparison.InvariantCultureIgnoreCase)) return "Test Drive invitation (LG/RUS) - 50 ea";
            else if (string.Equals(uid, "N338", StringComparison.InvariantCultureIgnoreCase)) return "Customer Journal (LG) - 10 ea";
            else if (string.Equals(uid, "N339", StringComparison.InvariantCultureIgnoreCase)) return "Customer Journal (RUS) - 10 ea";
            else if (string.Equals(uid, "003U", StringComparison.InvariantCultureIgnoreCase)) return "Ambassador pack - (LG)";
            else if (string.Equals(uid, "N739", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Club vouchers (LG) - 1 ea";
            else if (string.Equals(uid, "5802", StringComparison.InvariantCultureIgnoreCase)) return "Desk calendar 2019 (LG) - 1 ea";
            else if (string.Equals(uid, "N878", StringComparison.InvariantCultureIgnoreCase)) return "Diary (LG) - 1 ea";
            else if (string.Equals(uid, "N978", StringComparison.InvariantCultureIgnoreCase)) return "WLC – 0 Lesson (LG) - 1 ea";
            else if (string.Equals(uid, "N980", StringComparison.InvariantCultureIgnoreCase)) return "WLC – 0 Lesson (RUS) - 1 ea";
            else if (string.Equals(uid, "043K", StringComparison.InvariantCultureIgnoreCase)) return "Culinary Recipe Book";
            else if (string.Equals(uid, "1232", StringComparison.InvariantCultureIgnoreCase)) return "Multivitamin Mineral  & Herbal Tablets  90 Tablets";
            else if (string.Equals(uid, "1233", StringComparison.InvariantCultureIgnoreCase)) return "PPP 200gm";
            else if (string.Equals(uid, "1236", StringComparison.InvariantCultureIgnoreCase)) return "Dinoshake -Strawberry";
            else if (string.Equals(uid, "1239", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Strawberry";
            else if (string.Equals(uid, "1247", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Vanilla";
            else if (string.Equals(uid, "1248", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Chocolate";
            else if (string.Equals(uid, "1249", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Mango";
            else if (string.Equals(uid, "1269", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Orange";
            else if (string.Equals(uid, "1278", StringComparison.InvariantCultureIgnoreCase)) return "Actived Fibre 90 Tablets";
            else if (string.Equals(uid, "1279", StringComparison.InvariantCultureIgnoreCase)) return "Dinoshake -Chocolate 200gm";
            else if (string.Equals(uid, "1293", StringComparison.InvariantCultureIgnoreCase)) return "Aloe Plus 60 Capsulas";
            else if (string.Equals(uid, "1569", StringComparison.InvariantCultureIgnoreCase)) return "PPP 400 gm";
            else if (string.Equals(uid, "2637", StringComparison.InvariantCultureIgnoreCase)) return "Niteworks";
            else if (string.Equals(uid, "2865", StringComparison.InvariantCultureIgnoreCase)) return "Active Fibre Complex";
            else if (string.Equals(uid, "3123", StringComparison.InvariantCultureIgnoreCase)) return "Cell-Activator New 60 tablets";
            else if (string.Equals(uid, "4114", StringComparison.InvariantCultureIgnoreCase)) return "Formula-1 Kulfi";
            else if (string.Equals(uid, "0111", StringComparison.InvariantCultureIgnoreCase)) return "Cell-U-Loss";
            else if (string.Equals(uid, "0077", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Control";
            else if (string.Equals(uid, "025K", StringComparison.InvariantCultureIgnoreCase)) return "Simply ProBiotic";
            else if (string.Equals(uid, "0555", StringComparison.InvariantCultureIgnoreCase)) return "Joint Support";
            else if (string.Equals(uid, "0065", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife 60 Softgels";
            else if (string.Equals(uid, "6705", StringComparison.InvariantCultureIgnoreCase)) return "Presnatation Book";
            else if (string.Equals(uid, "N235", StringComparison.InvariantCultureIgnoreCase)) return "Low Glycemic Index Guide";
            else if (string.Equals(uid, "6153", StringComparison.InvariantCultureIgnoreCase)) return "Brochuree Customer Planner Guide 1-Set(20)";
            else if (string.Equals(uid, "6154", StringComparison.InvariantCultureIgnoreCase)) return "Brochure Customer Index Cards 1 -set(20)";
            else if (string.Equals(uid, "N277", StringComparison.InvariantCultureIgnoreCase)) return "Calcium Factsheet Pack";
            else if (string.Equals(uid, "6407", StringComparison.InvariantCultureIgnoreCase)) return "Weight Management Meal Planner";
            else if (string.Equals(uid, "6463", StringComparison.InvariantCultureIgnoreCase)) return "Flyer-Dinokid 1-Set(25)";
            else if (string.Equals(uid, "5288", StringComparison.InvariantCultureIgnoreCase)) return "Paper Cups 1-set(100)";
            else if (string.Equals(uid, "295A", StringComparison.InvariantCultureIgnoreCase)) return "HLN improved Shaker Cup Individual(Single)";
            else if (string.Equals(uid, "4275", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife 4-sided Spoon 1-set(10)";
            else if (string.Equals(uid, "P424", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Coffee Mug each";
            else if (string.Equals(uid, "N318", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Nutrition 500ml paper Cup";
            else if (string.Equals(uid, "N912", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife-2019 Calender";
            else if (string.Equals(uid, "N913", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife-2019 Dairy";
            else if (string.Equals(uid, "8847", StringComparison.InvariantCultureIgnoreCase)) return "Tablet Box -Medium size with 7 Copartment Each";
            else if (string.Equals(uid, "N022", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Non-woven Bag Large";
            else if (string.Equals(uid, "N023", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Non-woven bag Small";
            else if (string.Equals(uid, "7994", StringComparison.InvariantCultureIgnoreCase)) return "Button-Lose Weight  Now Each";
            else if (string.Equals(uid, "8144", StringComparison.InvariantCultureIgnoreCase)) return "Button-Work from Home Ask me how each";
            else if (string.Equals(uid, "901P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Note Book";
            else if (string.Equals(uid, "906P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Face Towel";
            else if (string.Equals(uid, "904P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded yoga Mat";
            else if (string.Equals(uid, "894P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Hand Towel";
            else if (string.Equals(uid, "050A", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Travel Mug";
            else if (string.Equals(uid, "896P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Key Chain";
            else if (string.Equals(uid, "053A", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Gym Bag With Yoga Mat";
            else if (string.Equals(uid, "898P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded 3-in-1 Pen with Laser Pointer";
            else if (string.Equals(uid, "903P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Big Bath Towel";
            else if (string.Equals(uid, "897P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBrandedMobile Holder Grip Base";
            else if (string.Equals(uid, "895P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded USB Light Stick";
            else if (string.Equals(uid, "054A", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Backpack";
            else if (string.Equals(uid, "905P", StringComparison.InvariantCultureIgnoreCase)) return "HerbalifeBranded Car Charger";
            else if (string.Equals(uid, "052A", StringComparison.InvariantCultureIgnoreCase)) return "Loyalty Program Herbalife Branded Notebook & Pen";
            else if (string.Equals(uid, "893P", StringComparison.InvariantCultureIgnoreCase)) return "Loyalty Program Herbalife Branded Pen";
            else if (string.Equals(uid, "899P", StringComparison.InvariantCultureIgnoreCase)) return "Loyalty Program Herbalife Branded Polycarbonate Slipper";
            else if (string.Equals(uid, "T167", StringComparison.InvariantCultureIgnoreCase)) return "Men's Nutrition Club T-shirt-Red-M";
            else if (string.Equals(uid, "T166", StringComparison.InvariantCultureIgnoreCase)) return "Women's Nutrition Club T-shirt-Pink-XL";
            else if (string.Equals(uid, "251A", StringComparison.InvariantCultureIgnoreCase)) return "Easy to carry Ipad case in Blue";
            else if (string.Equals(uid, "N714", StringComparison.InvariantCultureIgnoreCase)) return "Paper Cup 350ml Pack of 100 (Green)";
            else if (string.Equals(uid, "N715", StringComparison.InvariantCultureIgnoreCase)) return "Paper Cup 350ml Pack of 100";
            else if (string.Equals(uid, "4463", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - strawberry delight";
            else if (string.Equals(uid, "1295", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Lemon 50 g";
            else if (string.Equals(uid, "1291", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Ginger 50 g";
            else if (string.Equals(uid, "1296", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Peach 50 g";
            else if (string.Equals(uid, "1294", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Elaichi 50 g";
            else if (string.Equals(uid, "1238", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Cinnamon 50 g";
            else if (string.Equals(uid, "020N", StringComparison.InvariantCultureIgnoreCase)) return "Small Paper Bags";
            else if (string.Equals(uid, "021N", StringComparison.InvariantCultureIgnoreCase)) return "Medium Paper Bags";
            else if (string.Equals(uid, "2789", StringComparison.InvariantCultureIgnoreCase)) return "Health Supplement: Formula 1 Nutritional Shake Mix - Mint Chocolate";
            else if (string.Equals(uid, "2631", StringComparison.InvariantCultureIgnoreCase)) return "Health Supplement: Herbal Aloe Concentrate - Mandarin Flavor";
            else if (string.Equals(uid, "449Z", StringComparison.InvariantCultureIgnoreCase)) return "Set of 3 culinary recipe books + poster - russian language";
            else if (string.Equals(uid, "4467", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Cookie Crunch";
            else if (string.Equals(uid, "1171", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Cappuccino";
            else if (string.Equals(uid, "0946", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Passion fruit";
            else if (string.Equals(uid, "0950", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Pina Colada";
            else if (string.Equals(uid, "2793", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 melon";
            else if (string.Equals(uid, "0940", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 cream brulee";
            else if (string.Equals(uid, "0955", StringComparison.InvariantCultureIgnoreCase)) return "Formual 1 cream and cookies";
            else if (string.Equals(uid, "1636", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 evening intake";
            else if (string.Equals(uid, "2653", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 Vailla (7 packs)";
            else if (string.Equals(uid, "178A", StringComparison.InvariantCultureIgnoreCase)) return "3 days trial pack";
            else if (string.Equals(uid, "005K", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 melon (2kg)";
            else if (string.Equals(uid, "0258", StringComparison.InvariantCultureIgnoreCase)) return "Protein bar - Almond";
            else if (string.Equals(uid, "0259", StringComparison.InvariantCultureIgnoreCase)) return "Protein bar - Chocolate & Peanuts";
            else if (string.Equals(uid, "0265", StringComparison.InvariantCultureIgnoreCase)) return "Water filter";
            else if (string.Equals(uid, "0266", StringComparison.InvariantCultureIgnoreCase)) return "Cartridge for water filter";
            else if (string.Equals(uid, "0255", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Tea Concentrate - Natural Lemon Flavor 50g";
            else if (string.Equals(uid, "0256", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Tea Concentrate - Natural Raspberries Flavor 50g";
            else if (string.Equals(uid, "3151", StringComparison.InvariantCultureIgnoreCase)) return "LIFTOFF® - Orange";
            else if (string.Equals(uid, "1466", StringComparison.InvariantCultureIgnoreCase)) return "CR-7";
            else if (string.Equals(uid, "0036", StringComparison.InvariantCultureIgnoreCase)) return "Niteworks";
            else if (string.Equals(uid, "1189", StringComparison.InvariantCultureIgnoreCase)) return "Aloe Concentrate - Cranberries flavor";
            else if (string.Equals(uid, "0022", StringComparison.InvariantCultureIgnoreCase)) return "Sсhizandra Advanced";
            else if (string.Equals(uid, "0122", StringComparison.InvariantCultureIgnoreCase)) return "N-R-G Tablets";
            else if (string.Equals(uid, "0102", StringComparison.InvariantCultureIgnoreCase)) return "N-R-G Tea";
            else if (string.Equals(uid, "1437", StringComparison.InvariantCultureIgnoreCase)) return "HERBALIFE24® REBUILD STRENGTH";
            else if (string.Equals(uid, "1745", StringComparison.InvariantCultureIgnoreCase)) return "Formuala 2 for MEN";
            else if (string.Equals(uid, "2038", StringComparison.InvariantCultureIgnoreCase)) return "Formula 2 for WOMEN";
            else if (string.Equals(uid, "2273", StringComparison.InvariantCultureIgnoreCase)) return "Immune booster";
            else if (string.Equals(uid, "0707", StringComparison.InvariantCultureIgnoreCase)) return "Hand cream \"White tea\"";
            else if (string.Equals(uid, "0708", StringComparison.InvariantCultureIgnoreCase)) return "Foot cream \"White tea\"";
            else if (string.Equals(uid, "136A", StringComparison.InvariantCultureIgnoreCase)) return "Notebook with Herbalife logo";
            else if (string.Equals(uid, "8346", StringComparison.InvariantCultureIgnoreCase)) return "Значки с трилистником Herbalife Nutrition, цвет золота (5 шт.)";
            else if (string.Equals(uid, "8347", StringComparison.InvariantCultureIgnoreCase)) return "Значки с трилистником Herbalife Nutrition, цвет серебра (5 шт.)";
            else if (string.Equals(uid, "8459", StringComparison.InvariantCultureIgnoreCase)) return "Значок Wellness консультант (10 шт.)";
            else if (string.Equals(uid, "8414", StringComparison.InvariantCultureIgnoreCase)) return "Воздушные шары с логотипом Herbalife Nutrition (100 шт.)";
            else if (string.Equals(uid, "8787", StringComparison.InvariantCultureIgnoreCase)) return "Фартук Herbalife Nutrition";
            else if (string.Equals(uid, "8788", StringComparison.InvariantCultureIgnoreCase)) return "Новая бутылка для воды Herbalife Nutrition";
            else if (string.Equals(uid, "8550", StringComparison.InvariantCultureIgnoreCase)) return "Значок «Бросьте вызов лишнему весу» (10 шт.)";
            else if (string.Equals(uid, "I004", StringComparison.InvariantCultureIgnoreCase)) return "Магнит «Сбалансированный завтрак»";
            else if (string.Equals(uid, "076A", StringComparison.InvariantCultureIgnoreCase)) return "Большой значок «Я люблю Herbalife» (5 шт.)";
            else if (string.Equals(uid, "141A", StringComparison.InvariantCultureIgnoreCase)) return "Шейкер для коктейля с лого Herbalife Nutrition";
            else if (string.Equals(uid, "8289", StringComparison.InvariantCultureIgnoreCase)) return "Брендированный термо-стакан";
            else if (string.Equals(uid, "002A", StringComparison.InvariantCultureIgnoreCase)) return "Бьюти-кейс Herbalife SKIN";
            else if (string.Equals(uid, "216A", StringComparison.InvariantCultureIgnoreCase)) return "Значок Herbalife SKIN (5 шт.)";
            else if (string.Equals(uid, "274U", StringComparison.InvariantCultureIgnoreCase)) return "Набор Квалифицированного продюсера (со значком)";
            else if (string.Equals(uid, "270U", StringComparison.InvariantCultureIgnoreCase)) return "Набор Старшего консультанта (со значком)";
            else if (string.Equals(uid, "271U", StringComparison.InvariantCultureIgnoreCase)) return "Набор Строителя успеха (со значком)";
            else if (string.Equals(uid, "219A", StringComparison.InvariantCultureIgnoreCase)) return "Сумка женская SKIN светло-серая";
            else if (string.Equals(uid, "A548", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая мужская черная H24, S";
            else if (string.Equals(uid, "A549", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая мужская черная H24, M";
            else if (string.Equals(uid, "A550", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая мужская черная H24, L";
            else if (string.Equals(uid, "A551", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая мужская черная H24, размер XL";
            else if (string.Equals(uid, "A552", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая женская черная H24, S";
            else if (string.Equals(uid, "A553", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая женская черная H24, M";
            else if (string.Equals(uid, "A554", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая женская черная H24, L";
            else if (string.Equals(uid, "A555", StringComparison.InvariantCultureIgnoreCase)) return "Футболка хлопковая женская черная H24, XL";
            else if (string.Equals(uid, "A564", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная мужcкая черная H24, S";
            else if (string.Equals(uid, "A565", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная мужcкая черная H24, M";
            else if (string.Equals(uid, "A566", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная мужcкая черная H24, X";
            else if (string.Equals(uid, "A567", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная мужcкая черная H24, XL";
            else if (string.Equals(uid, "A568", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная женская черная H24, S";
            else if (string.Equals(uid, "A569", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная женская черная H24, M";
            else if (string.Equals(uid, "A570", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная женская черная H24, X";
            else if (string.Equals(uid, "A571", StringComparison.InvariantCultureIgnoreCase)) return "Футболка спортивная женская черная H24, XL";
            else if (string.Equals(uid, "A556", StringComparison.InvariantCultureIgnoreCase)) return "Поло мужское черное с длинным рукавом H24, S";
            else if (string.Equals(uid, "A557", StringComparison.InvariantCultureIgnoreCase)) return "Поло мужское черное с длинным рукавом H24, M";
            else if (string.Equals(uid, "A558", StringComparison.InvariantCultureIgnoreCase)) return "Поло мужское черное с длинным рукавом H24, X";
            else if (string.Equals(uid, "A559", StringComparison.InvariantCultureIgnoreCase)) return "Поло мужское черное с длинным рукавом H24, XL";
            else if (string.Equals(uid, "A560", StringComparison.InvariantCultureIgnoreCase)) return "Поло женское черное с длинным рукавом H24, S";
            else if (string.Equals(uid, "A561", StringComparison.InvariantCultureIgnoreCase)) return "Поло женское черное с длинным рукавом H24, M";
            else if (string.Equals(uid, "A562", StringComparison.InvariantCultureIgnoreCase)) return "Поло женское черное с длинным рукавом H24, X";
            else if (string.Equals(uid, "A563", StringComparison.InvariantCultureIgnoreCase)) return "Поло женское черное с длинным рукавом H24, XL";
            else if (string.Equals(uid, "A572", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором мужская спортивная с коротким рукавом, S";
            else if (string.Equals(uid, "A573", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором мужская спортивная с коротким рукавом, M";
            else if (string.Equals(uid, "A574", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором мужская спортивная с коротким рукавом, L";
            else if (string.Equals(uid, "A575", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором мужская спортивная с коротким рукавом, XL";
            else if (string.Equals(uid, "A576", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором женская спортивная с коротким рукавом, S";
            else if (string.Equals(uid, "A577", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором женская спортивная с коротким рукавом, M";
            else if (string.Equals(uid, "A578", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором женская спортивная с коротким рукавом, L";
            else if (string.Equals(uid, "A579", StringComparison.InvariantCultureIgnoreCase)) return "Футболка с узором женская спортивная с коротким рукавом, XL";
            else if (string.Equals(uid, "A882", StringComparison.InvariantCultureIgnoreCase)) return "Футболка сиреневая женская свободная, S";
            else if (string.Equals(uid, "A883", StringComparison.InvariantCultureIgnoreCase)) return "Футболка сиреневая женская свободная, M";
            else if (string.Equals(uid, "A884", StringComparison.InvariantCultureIgnoreCase)) return "Футболка сиреневая женская свободная, L";
            else if (string.Equals(uid, "A885", StringComparison.InvariantCultureIgnoreCase)) return "Футболка сиреневая женская свободная, XL";
            else if (string.Equals(uid, "A758", StringComparison.InvariantCultureIgnoreCase)) return "Толстовка мужская структурная, S";
            else if (string.Equals(uid, "A759", StringComparison.InvariantCultureIgnoreCase)) return "Толстовка мужская структурная, M";
            else if (string.Equals(uid, "A760", StringComparison.InvariantCultureIgnoreCase)) return "Толстовка мужская структурная, L";
            else if (string.Equals(uid, "A761", StringComparison.InvariantCultureIgnoreCase)) return "Толстовка мужская структурная, XL";
            else if (string.Equals(uid, "A786", StringComparison.InvariantCultureIgnoreCase)) return "Женский спортивный черный жилет, S";
            else if (string.Equals(uid, "A787", StringComparison.InvariantCultureIgnoreCase)) return "Женский спортивный черный жилет, M";
            else if (string.Equals(uid, "A788", StringComparison.InvariantCultureIgnoreCase)) return "Женский спортивный черный жилет, L";
            else if (string.Equals(uid, "A789", StringComparison.InvariantCultureIgnoreCase)) return "Женский спортивный черный жилет, XL";
            else if (string.Equals(uid, "A790", StringComparison.InvariantCultureIgnoreCase)) return "Женские длинные леггинсы с узором, S";
            else if (string.Equals(uid, "A791", StringComparison.InvariantCultureIgnoreCase)) return "Женские длинные леггинсы с узором, M";
            else if (string.Equals(uid, "A792", StringComparison.InvariantCultureIgnoreCase)) return "Женские длинные леггинсы с узором, L";
            else if (string.Equals(uid, "A793", StringComparison.InvariantCultureIgnoreCase)) return "Женские длинные леггинсы с узором, XL";
            else if (string.Equals(uid, "A794", StringComparison.InvariantCultureIgnoreCase)) return "Женское спортивное черное бра, S";
            else if (string.Equals(uid, "A795", StringComparison.InvariantCultureIgnoreCase)) return "Женское спортивное черное бра, M";
            else if (string.Equals(uid, "A796", StringComparison.InvariantCultureIgnoreCase)) return "Женское спортивное черное бра, L";
            else if (string.Equals(uid, "A797", StringComparison.InvariantCultureIgnoreCase)) return "Женское спортивное черное бра, XL";
            else if (string.Equals(uid, "A798", StringComparison.InvariantCultureIgnoreCase)) return "Женская спортивная свободная майка, S";
            else if (string.Equals(uid, "A799", StringComparison.InvariantCultureIgnoreCase)) return "Женская спортивная свободная майка, M";
            else if (string.Equals(uid, "A800", StringComparison.InvariantCultureIgnoreCase)) return "Женская спортивная свободная майка, L";
            else if (string.Equals(uid, "A801", StringComparison.InvariantCultureIgnoreCase)) return "Женская спортивная свободная майка, XL";
            else if (string.Equals(uid, "A802", StringComparison.InvariantCultureIgnoreCase)) return "Спортивные мужские утягивающие леггинсы H24, S";
            else if (string.Equals(uid, "A803", StringComparison.InvariantCultureIgnoreCase)) return "Спортивные мужские утягивающие леггинсы H24, M";
            else if (string.Equals(uid, "A804", StringComparison.InvariantCultureIgnoreCase)) return "Спортивные мужские утягивающие леггинсы H24, L";
            else if (string.Equals(uid, "A805", StringComparison.InvariantCultureIgnoreCase)) return "Спортивные мужские утягивающие леггинсы H24, XL";
            else if (string.Equals(uid, "A806", StringComparison.InvariantCultureIgnoreCase)) return "Мужской топ на молнии для бега H24, S";
            else if (string.Equals(uid, "A807", StringComparison.InvariantCultureIgnoreCase)) return "Мужской топ на молнии для бега H24, M";
            else if (string.Equals(uid, "A808", StringComparison.InvariantCultureIgnoreCase)) return "Мужской топ на молнии для бега H24, L";
            else if (string.Equals(uid, "A809", StringComparison.InvariantCultureIgnoreCase)) return "Мужской топ на молнии для бега H24, XL";
            else if (string.Equals(uid, "5588", StringComparison.InvariantCultureIgnoreCase)) return "Набор Независимого Партнера Herbalife Nutrition on-line";
            else if (string.Equals(uid, "9942", StringComparison.InvariantCultureIgnoreCase)) return "Bizworks (подписка на месяц)";
            else if (string.Equals(uid, "5942", StringComparison.InvariantCultureIgnoreCase)) return "Справочник по продукции Herbalife Nutrition";
            else if (string.Equals(uid, "6510", StringComparison.InvariantCultureIgnoreCase)) return "Брошюра «Правильный завтрак» (7 шт.)";
            else if (string.Equals(uid, "8673", StringComparison.InvariantCultureIgnoreCase)) return "Продуктовый каталог (10 шт.)";
            else if (string.Equals(uid, "5089", StringComparison.InvariantCultureIgnoreCase)) return "Тканевый постер «Марк Хьюз»";
            else if (string.Equals(uid, "8823", StringComparison.InvariantCultureIgnoreCase)) return "DVD-коллекция Джима Рона";
            else if (string.Equals(uid, "7759", StringComparison.InvariantCultureIgnoreCase)) return "Пакет Herbalife Nutrition зеленый маленький";
            else if (string.Equals(uid, "7760", StringComparison.InvariantCultureIgnoreCase)) return "Пакет Herbalife Nutrition зеленый большой";
            else if (string.Equals(uid, "8603", StringComparison.InvariantCultureIgnoreCase)) return "Пакет Herbalife Nutrition среднего размера";
            else if (string.Equals(uid, "5818", StringComparison.InvariantCultureIgnoreCase)) return "Wellness-тест (набор из 50 шт.)";
            else if (string.Equals(uid, "5995", StringComparison.InvariantCultureIgnoreCase)) return "Брошюра по Группам Поддержки (набор из 10 шт.)";
            else if (string.Equals(uid, "5819", StringComparison.InvariantCultureIgnoreCase)) return "Персональная Карточка и Программа питания (набор из 10 шт.)";
            else if (string.Equals(uid, "5060", StringComparison.InvariantCultureIgnoreCase)) return "Пособие участника Группы Поддержки";
            else if (string.Equals(uid, "6398", StringComparison.InvariantCultureIgnoreCase)) return "Ежедневник Herbalife Nutrition";
            else if (string.Equals(uid, "7905", StringComparison.InvariantCultureIgnoreCase)) return "Сертификаты «Попробуйте новую косметическую линию» (набор из 3 шт.)";
            else if (string.Equals(uid, "7887", StringComparison.InvariantCultureIgnoreCase)) return "Календарь настенный";
            else if (string.Equals(uid, "9598", StringComparison.InvariantCultureIgnoreCase)) return "Листовка c результатами клинических исследований (набор из 50 шт.)";
            else if (string.Equals(uid, "9749", StringComparison.InvariantCultureIgnoreCase)) return "Абонемент на посещение Клуба здорового образа жизни (набор из 50 шт.)";
            else if (string.Equals(uid, "9748", StringComparison.InvariantCultureIgnoreCase)) return "Приглашение в Клуб здорового образа жизни (набор из 50 шт.)";
            else if (string.Equals(uid, "5463", StringComparison.InvariantCultureIgnoreCase)) return "Презентационные материалы Herbalife Nutrition";
            else if (string.Equals(uid, "N182", StringComparison.InvariantCultureIgnoreCase)) return "Счетчик коктейлей Формула 1";
            else if (string.Equals(uid, "N151", StringComparison.InvariantCultureIgnoreCase)) return "Пакет Herbalife SKIN";
            else if (string.Equals(uid, "N016", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Посланники Бренда Herbalife Nutrition»";
            else if (string.Equals(uid, "N017", StringComparison.InvariantCultureIgnoreCase)) return "Постер «РоузГард»";
            else if (string.Equals(uid, "9182", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Протеиновый коктейль Формула 1»";
            else if (string.Equals(uid, "9183", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Завтрак»";
            else if (string.Equals(uid, "9185", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Рональдо»";
            else if (string.Equals(uid, "9187", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Наука»";
            else if (string.Equals(uid, "9189", StringComparison.InvariantCultureIgnoreCase)) return "Постер «CASA»";
            else if (string.Equals(uid, "9191", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Клинические исследования»";
            else if (string.Equals(uid, "5953", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Клуб здорового образа жизни»";
            else if (string.Equals(uid, "9193", StringComparison.InvariantCultureIgnoreCase)) return "Постер «Овсяно-яблочный напиток»";
            else if (string.Equals(uid, "7728", StringComparison.InvariantCultureIgnoreCase)) return "Подарочная лента (10 м)";
            else if (string.Equals(uid, "7729", StringComparison.InvariantCultureIgnoreCase)) return "Подарочные наклейки";
            else if (string.Equals(uid, "522U", StringComparison.InvariantCultureIgnoreCase)) return "Подарочный пакет Herbalife Nutrition";
            else if (string.Equals(uid, "9828", StringComparison.InvariantCultureIgnoreCase)) return "Ростомер с Самантой Клейтон";
            else if (string.Equals(uid, "N989", StringComparison.InvariantCultureIgnoreCase)) return "Стакан Амбассадора";
            else if (string.Equals(uid, "001N", StringComparison.InvariantCultureIgnoreCase)) return "Контейнер для Формулы1 -2кг";
            else if (string.Equals(uid, "8501", StringComparison.InvariantCultureIgnoreCase)) return "Значок «Хочешь похудеть» (набор из 10 шт.)";
            else if (string.Equals(uid, "183N", StringComparison.InvariantCultureIgnoreCase)) return "Продуктовый каталог";
            else if (string.Equals(uid, "G755", StringComparison.InvariantCultureIgnoreCase)) return "Water bottle HRBL NUT 900ml - 1 ea";
            else if (string.Equals(uid, "G756", StringComparison.InvariantCultureIgnoreCase)) return "HN 2L bottle - 1 ea";
            else if (string.Equals(uid, "G757", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Tote Bag - 1 ea";
            else if (string.Equals(uid, "G758", StringComparison.InvariantCultureIgnoreCase)) return "24H Smart shaker - 1 ea";
            else if (string.Equals(uid, "G759", StringComparison.InvariantCultureIgnoreCase)) return "24H Water bottle (750 ml) - 1 ea";
            else if (string.Equals(uid, "G760", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Nutrition sports bottle - small (500cc) - 1 ea";
            else if (string.Equals(uid, "9943", StringComparison.InvariantCultureIgnoreCase)) return "Bizworks (1 месяц) БЕСПЛАТНО";
            else if (string.Equals(uid, "4466", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Vanilla Creme";
            else if (string.Equals(uid, "1458", StringComparison.InvariantCultureIgnoreCase)) return "H24 Hydrate";
            else if (string.Equals(uid, "031K", StringComparison.InvariantCultureIgnoreCase)) return "H24 Rebuild Strength";
            else if (string.Equals(uid, "289N", StringComparison.InvariantCultureIgnoreCase)) return "Universal Gift Certificates - (LG) - 3 ea";
            else if (string.Equals(uid, "4468", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 – smooth chocolate";
            else if (string.Equals(uid, "0001", StringComparison.InvariantCultureIgnoreCase)) return "logo";
            else if (string.Equals(uid, "0002", StringComparison.InvariantCultureIgnoreCase)) return "test";
            else if (string.Equals(uid, "0144", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1-Tropical";
            else if (string.Equals(uid, "0145", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 STRICKLY KOSHER";
            else if (string.Equals(uid, "1432", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1-sport milk base";
            else if (string.Equals(uid, "5498", StringComparison.InvariantCultureIgnoreCase)) return "HMP KIT ARABIC";
            else if (string.Equals(uid, "5617", StringComparison.InvariantCultureIgnoreCase)) return "Mini Herbalife Member Pack (HMP)";
            else if (string.Equals(uid, "5629", StringComparison.InvariantCultureIgnoreCase)) return "Mini Herbalife Member Pack (HMP)";
            else if (string.Equals(uid, "628A", StringComparison.InvariantCultureIgnoreCase)) return "\"I love Herbalife\" Pin";
            else if (string.Equals(uid, "629A", StringComparison.InvariantCultureIgnoreCase)) return "\"I love Herbalife\" Pin";
            else if (string.Equals(uid, "1041", StringComparison.InvariantCultureIgnoreCase)) return "Shaker Cup";
            else if (string.Equals(uid, "1042", StringComparison.InvariantCultureIgnoreCase)) return "Shaker Cup";
            else if (string.Equals(uid, "1043", StringComparison.InvariantCultureIgnoreCase)) return "Shaker Cup";
            else if (string.Equals(uid, "1044", StringComparison.InvariantCultureIgnoreCase)) return "Shaker Cup";
            else if (string.Equals(uid, "1045", StringComparison.InvariantCultureIgnoreCase)) return "Shaker Cup";
            else if (string.Equals(uid, "508H", StringComparison.InvariantCultureIgnoreCase)) return "(HBL) TOTE BAG";
            else if (string.Equals(uid, "5776", StringComparison.InvariantCultureIgnoreCase)) return "PRODUCT BROCHURE ";
            else if (string.Equals(uid, "N947", StringComparison.InvariantCultureIgnoreCase)) return "SMALL PAPER BAGS 50 Units";
            else if (string.Equals(uid, "N946", StringComparison.InvariantCultureIgnoreCase)) return "MEDIUM PAPER BAGS 50 Units";
            else if (string.Equals(uid, "6940", StringComparison.InvariantCultureIgnoreCase)) return "Ortodox Product Brochure";
            else if (string.Equals(uid, "N153", StringComparison.InvariantCultureIgnoreCase)) return "Journal for NC (LG/HE) - 1 ea";
            else if (string.Equals(uid, "N154", StringComparison.InvariantCultureIgnoreCase)) return "Journal for NC (ARAR) - 1 ea";
            else if (string.Equals(uid, "N155", StringComparison.InvariantCultureIgnoreCase)) return "Journal for NC (RUS)";
            else if (string.Equals(uid, "N203", StringComparison.InvariantCultureIgnoreCase)) return "HIM BROCHURE HEBREW";
            else if (string.Equals(uid, "N204", StringComparison.InvariantCultureIgnoreCase)) return "HIM BROCHURE ARABIC";
            else if (string.Equals(uid, "N205", StringComparison.InvariantCultureIgnoreCase)) return "HIM BROCHURE RUSSIAN";
            else if (string.Equals(uid, "N992", StringComparison.InvariantCultureIgnoreCase)) return "F1 CLINICAL STUDIES BROCHURE (ARAR)";
            else if (string.Equals(uid, "N923", StringComparison.InvariantCultureIgnoreCase)) return "F1 CLINICAL STUDIES BROCHURE (HE)";
            else if (string.Equals(uid, "N924", StringComparison.InvariantCultureIgnoreCase)) return "F1 CLINICAL STUDIES BROCHURE(RUS)";
            else if (string.Equals(uid, "100V", StringComparison.InvariantCultureIgnoreCase)) return "TRAINING CENTER SUPERVISOR";
            else if (string.Equals(uid, "101V", StringComparison.InvariantCultureIgnoreCase)) return "TRAINING CENTER MEMBER";
            else if (string.Equals(uid, "102V", StringComparison.InvariantCultureIgnoreCase)) return "TRAINING CENTER HOURLY PAYMENT";
            else if (string.Equals(uid, "103V", StringComparison.InvariantCultureIgnoreCase)) return "TRAINING CENTER BUSINESS SEMINAR";
            else if (string.Equals(uid, "209N", StringComparison.InvariantCultureIgnoreCase)) return "Подарочная короба (10 шт)";
            else if (string.Equals(uid, "423N", StringComparison.InvariantCultureIgnoreCase)) return "Universal Gift Certificates - (RUS) - 3 ea";
            else if (string.Equals(uid, "046K", StringComparison.InvariantCultureIgnoreCase)) return "HN - Skin Booster - 30 Servings";
            else if (string.Equals(uid, "H161", StringComparison.InvariantCultureIgnoreCase)) return "HCPC";
            else if (string.Equals(uid, "719A", StringComparison.InvariantCultureIgnoreCase)) return "Measuring Spoon";
            else if (string.Equals(uid, "001K", StringComparison.InvariantCultureIgnoreCase)) return "Мини-батончики Ваниль";
            else if (string.Equals(uid, "002K", StringComparison.InvariantCultureIgnoreCase)) return "Мини-батончики Лимон";
            else if (string.Equals(uid, "051K", StringComparison.InvariantCultureIgnoreCase)) return "BETA HEART - VANILLA FLAVOUR";
            else if (string.Equals(uid, "080K", StringComparison.InvariantCultureIgnoreCase)) return "Afresh Energy Drink Mix Tulsi 50 g";
            else if (string.Equals(uid, "0104", StringComparison.InvariantCultureIgnoreCase)) return "Cell Active";
            else if (string.Equals(uid, "0267", StringComparison.InvariantCultureIgnoreCase)) return "Beta Heart";
            else if (string.Equals(uid, "0389", StringComparison.InvariantCultureIgnoreCase)) return "Starter Kit";
            else if (string.Equals(uid, "4469", StringComparison.InvariantCultureIgnoreCase)) return "F1 summer berries";
            else if (string.Equals(uid, "4470", StringComparison.InvariantCultureIgnoreCase)) return "F1 summer berries";
            else if (string.Equals(uid, "4471", StringComparison.InvariantCultureIgnoreCase)) return "Mint & Chocolate F1";
            else if (string.Equals(uid, "012K", StringComparison.InvariantCultureIgnoreCase)) return "HIGH PROTEIN";
            else if (string.Equals(uid, "013K", StringComparison.InvariantCultureIgnoreCase)) return "TRI BLEND";
            else if (string.Equals(uid, "048K", StringComparison.InvariantCultureIgnoreCase)) return "F1 Vanilla";
            else if (string.Equals(uid, "053K", StringComparison.InvariantCultureIgnoreCase)) return "Sachets Vanilla  creme F1";
            else if (string.Equals(uid, "054K", StringComparison.InvariantCultureIgnoreCase)) return "Sachets Cookie crunch F1";
            else if (string.Equals(uid, "382A", StringComparison.InvariantCultureIgnoreCase)) return "KIT TEST PRODUCT";
            else if (string.Equals(uid, "4465", StringComparison.InvariantCultureIgnoreCase)) return "F1 Milk & Coffe";
            else if (string.Equals(uid, "3968", StringComparison.InvariantCultureIgnoreCase)) return "Almond/Vanilla -  proteins bars";
            else if (string.Equals(uid, "3972", StringComparison.InvariantCultureIgnoreCase)) return "Peanuts/chocolate -  protein bars";
            else if (string.Equals(uid, "3976", StringComparison.InvariantCultureIgnoreCase)) return "Lemon -  protein bars";
            else if (string.Equals(uid, "3150", StringComparison.InvariantCultureIgnoreCase)) return "Niteworks";
            else if (string.Equals(uid, "3118", StringComparison.InvariantCultureIgnoreCase)) return "Free Formula 1 Vanilla";
            else if (string.Equals(uid, "2657", StringComparison.InvariantCultureIgnoreCase)) return "Cream - Formula 1 Sachets Cookies";
            else if (string.Equals(uid, "2600", StringComparison.InvariantCultureIgnoreCase)) return "Protein Drink Mix";
            else if (string.Equals(uid, "2554", StringComparison.InvariantCultureIgnoreCase)) return "Multi Fiber Drink";
            else if (string.Equals(uid, "1922", StringComparison.InvariantCultureIgnoreCase)) return "Vanilla (780g)";
            else if (string.Equals(uid, "1196", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Aloe Max 473ml";
            else if (string.Equals(uid, "1424", StringComparison.InvariantCultureIgnoreCase)) return "H24 Restore";
            else if (string.Equals(uid, "1433", StringComparison.InvariantCultureIgnoreCase)) return "H24 Hydrate";
            else if (string.Equals(uid, "1435", StringComparison.InvariantCultureIgnoreCase)) return "H24 Prolong";
            else if (string.Equals(uid, "1436", StringComparison.InvariantCultureIgnoreCase)) return "H24 Rebuild ~Endurance";
            else if (string.Equals(uid, "1467", StringComparison.InvariantCultureIgnoreCase)) return "CR7 Drive Box (sachets)";
            else if (string.Equals(uid, "1660", StringComparison.InvariantCultureIgnoreCase)) return "pro20 select";
            else if (string.Equals(uid, "N990", StringComparison.InvariantCultureIgnoreCase)) return "Preferred Customer APF";
            else if (string.Equals(uid, "3798", StringComparison.InvariantCultureIgnoreCase)) return "MINI HMP LET";
            else if (string.Equals(uid, "5039", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Recipes";
            else if (string.Equals(uid, "5047", StringComparison.InvariantCultureIgnoreCase)) return "Flyer Wellness Program";
            else if (string.Equals(uid, "5127", StringComparison.InvariantCultureIgnoreCase)) return "Order Proposal Form";
            else if (string.Equals(uid, "5197", StringComparison.InvariantCultureIgnoreCase)) return "Purchase receipt retail";
            else if (string.Equals(uid, "5205", StringComparison.InvariantCultureIgnoreCase)) return "International Business Oportunity";
            else if (string.Equals(uid, "5287", StringComparison.InvariantCultureIgnoreCase)) return "Recipes Folder";
            else if (string.Equals(uid, "5631", StringComparison.InvariantCultureIgnoreCase)) return "Business Evaluation";
            else if (string.Equals(uid, "5724", StringComparison.InvariantCultureIgnoreCase)) return "Soy Nuts Brochure";
            else if (string.Equals(uid, "6045", StringComparison.InvariantCultureIgnoreCase)) return "H24 Brochure";
            else if (string.Equals(uid, "6149", StringComparison.InvariantCultureIgnoreCase)) return "Manual \"International Business Opportunity\"";
            else if (string.Equals(uid, "6688", StringComparison.InvariantCultureIgnoreCase)) return "Survey Nutrition  and wellness";
            else if (string.Equals(uid, "6767", StringComparison.InvariantCultureIgnoreCase)) return "Wellness Evaluation Book";
            else if (string.Equals(uid, "0", StringComparison.InvariantCultureIgnoreCase)) return "Inserts Today";
            else if (string.Equals(uid, "7028", StringComparison.InvariantCultureIgnoreCase)) return "Gift Vouchers facial";
            else if (string.Equals(uid, "8648", StringComparison.InvariantCultureIgnoreCase)) return "Manual 20 Steps to Success";
            else if (string.Equals(uid, "9771", StringComparison.InvariantCultureIgnoreCase)) return "Ring Binder (for Information Guide products)";
            else if (string.Equals(uid, "9950", StringComparison.InvariantCultureIgnoreCase)) return "Book presentation - Ring Binger";
            else if (string.Equals(uid, "E584", StringComparison.InvariantCultureIgnoreCase)) return "HFF Donation";
            else if (string.Equals(uid, "H162", StringComparison.InvariantCultureIgnoreCase)) return "HPCP LET";
            else if (string.Equals(uid, "N230", StringComparison.InvariantCultureIgnoreCase)) return "Sheet of the Wellness Assesment for Tanita";
            else if (string.Equals(uid, "N324", StringComparison.InvariantCultureIgnoreCase)) return "Welfare Assessment for Tanita Sports";
            else if (string.Equals(uid, "N438", StringComparison.InvariantCultureIgnoreCase)) return "MAP Brochure";
            else if (string.Equals(uid, "N441", StringComparison.InvariantCultureIgnoreCase)) return "Protocol 1";
            else if (string.Equals(uid, "N561", StringComparison.InvariantCultureIgnoreCase)) return "Protocol 2";
            else if (string.Equals(uid, "N562", StringComparison.InvariantCultureIgnoreCase)) return "Price List";
            else if (string.Equals(uid, "N773", StringComparison.InvariantCultureIgnoreCase)) return "Protocol 3";
            else if (string.Equals(uid, "N929", StringComparison.InvariantCultureIgnoreCase)) return "Protocol 4";
            else if (string.Equals(uid, "U694", StringComparison.InvariantCultureIgnoreCase)) return "DVD 24 FIT";
            else if (string.Equals(uid, "N181", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife SKIN gift bag and tissue paper set";
            else if (string.Equals(uid, "N168", StringComparison.InvariantCultureIgnoreCase)) return "Folders Herbalife";
            else if (string.Equals(uid, "099A", StringComparison.InvariantCultureIgnoreCase)) return "SKIN Spin";
            else if (string.Equals(uid, "6467", StringComparison.InvariantCultureIgnoreCase)) return "Omron";
            else if (string.Equals(uid, "6683", StringComparison.InvariantCultureIgnoreCase)) return "Biodegradable bags with Herbalife Logo";
            else if (string.Equals(uid, "6700", StringComparison.InvariantCultureIgnoreCase)) return "Paper Bags with Herbalife Logo";
            else if (string.Equals(uid, "6922", StringComparison.InvariantCultureIgnoreCase)) return "Paper Bags Herbalife - Big";
            else if (string.Equals(uid, "6923", StringComparison.InvariantCultureIgnoreCase)) return "Paper Bags Herbalife - Small";
            else if (string.Equals(uid, "8461", StringComparison.InvariantCultureIgnoreCase)) return "Success Builder Pin";
            else if (string.Equals(uid, "8498", StringComparison.InvariantCultureIgnoreCase)) return "Qualified Producer (5units)";
            else if (string.Equals(uid, "8515", StringComparison.InvariantCultureIgnoreCase)) return "Personal Coach pin";
            else if (string.Equals(uid, "8640", StringComparison.InvariantCultureIgnoreCase)) return "Big Containers F1 (10 untis)";
            else if (string.Equals(uid, "8643", StringComparison.InvariantCultureIgnoreCase)) return "Big Shaker";
            else if (string.Equals(uid, "8782", StringComparison.InvariantCultureIgnoreCase)) return "Have You Had Your Shake Today";
            else if (string.Equals(uid, "0789", StringComparison.InvariantCultureIgnoreCase)) return "Button Free Demostration";
            else if (string.Equals(uid, "151A", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Ballpoint Pen";
            else if (string.Equals(uid, "245A", StringComparison.InvariantCultureIgnoreCase)) return "CR7 DRIVE Sport Bottle";
            else if (string.Equals(uid, "247A", StringComparison.InvariantCultureIgnoreCase)) return "SPOON (SINGLE)";
            else if (string.Equals(uid, "300A", StringComparison.InvariantCultureIgnoreCase)) return "Spoons";
            else if (string.Equals(uid, "A727", StringComparison.InvariantCultureIgnoreCase)) return "SMALL TABLET BOX";
            else if (string.Equals(uid, "459N", StringComparison.InvariantCultureIgnoreCase)) return "(RS) Sports Book “With taste about sport” - 1 ea";
            else if (string.Equals(uid, "149A", StringComparison.InvariantCultureIgnoreCase)) return "Trial Pack";
            else if (string.Equals(uid, "9035", StringComparison.InvariantCultureIgnoreCase)) return "Product Brochure";
            else if (string.Equals(uid, "1237", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Chocolate Mint (Formula 1)";
            else if (string.Equals(uid, "1227", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - CREAMY COFFEE (Formula 1)";
            else if (string.Equals(uid, "096K", StringComparison.InvariantCultureIgnoreCase)) return "Express Protein bars - chocolate flavour";
            else if (string.Equals(uid, "1209", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Dulce (Formula 1)";
            else if (string.Equals(uid, "3127", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Vanila (Formula 1)";
            else if (string.Equals(uid, "3128", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Chocolate (Formula 1)";
            else if (string.Equals(uid, "3129", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Strawberry (Formula 1)";
            else if (string.Equals(uid, "3199", StringComparison.InvariantCultureIgnoreCase)) return "Healthy Meal - Cookies'n Cream (Formula 1)";
            else if (string.Equals(uid, "0917", StringComparison.InvariantCultureIgnoreCase)) return "Multivitamin Mineral Complex (Formula 2)";
            else if (string.Equals(uid, "0194", StringComparison.InvariantCultureIgnoreCase)) return "Personalized Protein Powder (Formula 3)";
            else if (string.Equals(uid, "1412", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife24 Formula 1 Sport";
            else if (string.Equals(uid, "1463", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife24 Formula 1 Sport";
            else if (string.Equals(uid, "2841", StringComparison.InvariantCultureIgnoreCase)) return "Healty I";
            else if (string.Equals(uid, "0056", StringComparison.InvariantCultureIgnoreCase)) return "Beauty Power Drink";
            else if (string.Equals(uid, "3126", StringComparison.InvariantCultureIgnoreCase)) return "Calcium Plus Vitamin D";
            else if (string.Equals(uid, "1076", StringComparison.InvariantCultureIgnoreCase)) return "Prolessa Duo";
            else if (string.Equals(uid, "2037", StringComparison.InvariantCultureIgnoreCase)) return "Chitosan Plus";
            else if (string.Equals(uid, "0083", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Aloe Gel - Origianl";
            else if (string.Equals(uid, "0132", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Aloe Gel - Mango";
            else if (string.Equals(uid, "0075", StringComparison.InvariantCultureIgnoreCase)) return "Probiotic Complex";
            else if (string.Equals(uid, "1500", StringComparison.InvariantCultureIgnoreCase)) return "NEW CoQ10 Plus";
            else if (string.Equals(uid, "2827", StringComparison.InvariantCultureIgnoreCase)) return "Gamma Linolenic Acid Plus";
            else if (string.Equals(uid, "0063", StringComparison.InvariantCultureIgnoreCase)) return "Herbaflex Glucosamine";
            else if (string.Equals(uid, "0049", StringComparison.InvariantCultureIgnoreCase)) return "Snack Defense Advanced";
            else if (string.Equals(uid, "0100", StringComparison.InvariantCultureIgnoreCase)) return "Tri-Shield";
            else if (string.Equals(uid, "0210", StringComparison.InvariantCultureIgnoreCase)) return "Chitosan Fibre Complex";
            else if (string.Equals(uid, "0271", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Cookies 'n Cream";
            else if (string.Equals(uid, "0279", StringComparison.InvariantCultureIgnoreCase)) return "Triple Berry Complex";
            else if (string.Equals(uid, "0565", StringComparison.InvariantCultureIgnoreCase)) return "Xtra-Cal Advanced";
            else if (string.Equals(uid, "0566", StringComparison.InvariantCultureIgnoreCase)) return "Tang Kuei";
            else if (string.Equals(uid, "1000", StringComparison.InvariantCultureIgnoreCase)) return "Joint Support";
            else if (string.Equals(uid, "1207", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Mint Chocolate";
            else if (string.Equals(uid, "1427", StringComparison.InvariantCultureIgnoreCase)) return "Green Tea-Original";
            else if (string.Equals(uid, "1428", StringComparison.InvariantCultureIgnoreCase)) return "Green Tea-Pomegranate";
            else if (string.Equals(uid, "1829", StringComparison.InvariantCultureIgnoreCase)) return "Simply Probiotic";
            else if (string.Equals(uid, "2121", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Concentrate-Honey Ginger";
            else if (string.Equals(uid, "2335", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Fruity Mango";
            else if (string.Equals(uid, "2487", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Café Latte";
            else if (string.Equals(uid, "2770", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Vanilla";
            else if (string.Equals(uid, "2771", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Chocolate";
            else if (string.Equals(uid, "2772", StringComparison.InvariantCultureIgnoreCase)) return "Nutrition Protein Drink Mix-Strawberry";
            else if (string.Equals(uid, "3122", StringComparison.InvariantCultureIgnoreCase)) return "Multi-Vitamin";
            else if (string.Equals(uid, "3272", StringComparison.InvariantCultureIgnoreCase)) return "Garden 7";
            else if (string.Equals(uid, "H193", StringComparison.InvariantCultureIgnoreCase)) return "Herbalife Member Pack - Chinese";
            else if (string.Equals(uid, "8789", StringComparison.InvariantCultureIgnoreCase)) return "Button Free Demostration";
            else if (string.Equals(uid, "I041", StringComparison.InvariantCultureIgnoreCase)) return "Green Neon Shaker (1 Unit)";
            else if (string.Equals(uid, "I042", StringComparison.InvariantCultureIgnoreCase)) return "Blue Neon Shaker (1 Unit)";
            else if (string.Equals(uid, "I043", StringComparison.InvariantCultureIgnoreCase)) return "Orange Neon Shaker (1 Unit)";
            else if (string.Equals(uid, "I044", StringComparison.InvariantCultureIgnoreCase)) return "Pink Neon Shaker (1 Unit)";
            else if (string.Equals(uid, "I045", StringComparison.InvariantCultureIgnoreCase)) return "Purple Neon Shaker (1 Unit)";
            else if (string.Equals(uid, "4461", StringComparison.InvariantCultureIgnoreCase)) return "F1 Sport Vanilla Cream";
            else if (string.Equals(uid, "391H", StringComparison.InvariantCultureIgnoreCase)) return "HFF - SPAIN CASA HERBALIFE PROGRAM";
            else if (string.Equals(uid, "S202", StringComparison.InvariantCultureIgnoreCase)) return "TODAY MAG-FREE 1";
            else if (string.Equals(uid, "052K", StringComparison.InvariantCultureIgnoreCase)) return "TRI BLEND- Coffee and Caramel";
            else if (string.Equals(uid, "1610", StringComparison.InvariantCultureIgnoreCase)) return "Herbal Aloe Concentrate";
            else if (string.Equals(uid, "670N", StringComparison.InvariantCultureIgnoreCase)) return "Product Brochure (LG) - 1 ea";
            else if (string.Equals(uid, "749N", StringComparison.InvariantCultureIgnoreCase)) return "Product Brochure (RS) - 1 ea";
            else if (string.Equals(uid, "0748", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 - Chicken Cream Soup";
            else if (string.Equals(uid, "00H5", StringComparison.InvariantCultureIgnoreCase)) return "HNF (HBL) PINK BOTTLE";
            else if (string.Equals(uid, "00H6", StringComparison.InvariantCultureIgnoreCase)) return "HNF (HBL) BLUE BOTTLE";
            else if (string.Equals(uid, "00H7", StringComparison.InvariantCultureIgnoreCase)) return "HNF (HBL) GREEN BOTTLE";
            else if (string.Equals(uid, "test", StringComparison.InvariantCultureIgnoreCase)) return "test";
            else if (string.Equals(uid, "test2", StringComparison.InvariantCultureIgnoreCase)) return "test2";
            else if (string.Equals(uid, "986N", StringComparison.InvariantCultureIgnoreCase)) return "(LG) Sports Book “With taste about sport” - 1 ea";
            else if (string.Equals(uid, "H228", StringComparison.InvariantCultureIgnoreCase)) return "Набор привилегированного клиента офлайн";
            else if (string.Equals(uid, "H230", StringComparison.InvariantCultureIgnoreCase)) return "Переходный  набор из ПК в НП офлайн";
            else if (string.Equals(uid, "H231", StringComparison.InvariantCultureIgnoreCase)) return "Набор независимого партнёра офлайн";
            else if (string.Equals(uid, "513M", StringComparison.InvariantCultureIgnoreCase)) return "GREEN BAG";
            else if (string.Equals(uid, "082K", StringComparison.InvariantCultureIgnoreCase)) return "Formula 1 Nutritional Shake Mix Banana Caramel 500 g";
            else if (string.Equals(uid, "N387", StringComparison.InvariantCultureIgnoreCase)) return "New Associate Application";
            else if (string.Equals(uid, "N396", StringComparison.InvariantCultureIgnoreCase)) return "Preferred  Customer  Application";
            else if (string.Equals(uid, "094K", StringComparison.InvariantCultureIgnoreCase)) return "ShakeMate";
            else if (string.Equals(uid, "0757", StringComparison.InvariantCultureIgnoreCase)) return "ALOE CONCENTRATE - MANGO FLAVOR";

            return uid;
        }
    }
}
