using System;
using System.Collections.Generic;

namespace Filuet.ASC.Kiosk.OnBoard.UVS.Abstractions.Entities
{
    public partial class Zetai4
    {
        public int Id { get; set; }
        public int? ApId { get; set; }
        public int? Znr { get; set; }
        public int? TaxCount { get; set; }
        public int? Payments { get; set; }
        public int? DepCount { get; set; }
        public int? Payouts { get; set; }
        public int? Returns { get; set; }
        public int? Refunds { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? LastCheck { get; set; }
        public int? CheckCount { get; set; }
        public int? ReturnCount { get; set; }
        public double? Discount { get; set; }
        public double? Surcharge { get; set; }
        public double? Cash { get; set; }
        public double? CashIn { get; set; }
        public double? CashOut { get; set; }
        public double? Payout { get; set; }
        public double? PayoutReturn { get; set; }
        public double? Refund { get; set; }
        public double? RefundReturn { get; set; }
        public double? Sell1Total { get; set; }
        public double? Sell1Tax1Total { get; set; }
        public double? Sell1Tax1Tax { get; set; }
        public double? Sell1Tax2Total { get; set; }
        public double? Sell1Tax2Tax { get; set; }
        public double? Sell1Tax3Total { get; set; }
        public double? Sell1Tax3Tax { get; set; }
        public double? Sell1Tax4Total { get; set; }
        public double? Sell1Tax4Tax { get; set; }
        public double? Sell2Total { get; set; }
        public double? Sell2Tax1Total { get; set; }
        public double? Sell2Tax1Tax { get; set; }
        public double? Sell2Tax2Total { get; set; }
        public double? Sell2Tax2Tax { get; set; }
        public double? Sell2Tax3Total { get; set; }
        public double? Sell2Tax3Tax { get; set; }
        public double? Sell2Tax4Total { get; set; }
        public double? Sell2Tax4Tax { get; set; }
        public double? Sell3Total { get; set; }
        public double? Sell3Tax1Total { get; set; }
        public double? Sell3Tax1Tax { get; set; }
        public double? Sell3Tax2Total { get; set; }
        public double? Sell3Tax2Tax { get; set; }
        public double? Sell3Tax3Total { get; set; }
        public double? Sell3Tax3Tax { get; set; }
        public double? Sell3Tax4Total { get; set; }
        public double? Sell3Tax4Tax { get; set; }
        public double? Sell4Total { get; set; }
        public double? Sell4Tax1Total { get; set; }
        public double? Sell4Tax1Tax { get; set; }
        public double? Sell4Tax2Total { get; set; }
        public double? Sell4Tax2Tax { get; set; }
        public double? Sell4Tax3Total { get; set; }
        public double? Sell4Tax3Tax { get; set; }
        public double? Sell4Tax4Total { get; set; }
        public double? Sell4Tax4Tax { get; set; }
        public double? Return1Total { get; set; }
        public double? Return1Tax1Total { get; set; }
        public double? Return1Tax1Tax { get; set; }
        public double? Return1Tax2Total { get; set; }
        public double? Return1Tax2Tax { get; set; }
        public double? Return1Tax3Total { get; set; }
        public double? Return1Tax3Tax { get; set; }
        public double? Return1Tax4Total { get; set; }
        public double? Return1Tax4Tax { get; set; }
        public double? Return2Total { get; set; }
        public double? Return2Tax1Total { get; set; }
        public double? Return2Tax1Tax { get; set; }
        public double? Return2Tax2Total { get; set; }
        public double? Return2Tax2Tax { get; set; }
        public double? Return2Tax3Total { get; set; }
        public double? Return2Tax3Tax { get; set; }
        public double? Return2Tax4Total { get; set; }
        public double? Return2Tax4Tax { get; set; }
        public double? Return3Total { get; set; }
        public double? Return3Tax1Total { get; set; }
        public double? Return3Tax1Tax { get; set; }
        public double? Return3Tax2Total { get; set; }
        public double? Return3Tax2Tax { get; set; }
        public double? Return3Tax3Total { get; set; }
        public double? Return3Tax3Tax { get; set; }
        public double? Return3Tax4Total { get; set; }
        public double? Return3Tax4Tax { get; set; }
        public double? Return4Total { get; set; }
        public double? Return4Tax1Total { get; set; }
        public double? Return4Tax1Tax { get; set; }
        public double? Return4Tax2Total { get; set; }
        public double? Return4Tax2Tax { get; set; }
        public double? Return4Tax3Total { get; set; }
        public double? Return4Tax3Tax { get; set; }
        public double? Return4Tax4Total { get; set; }
        public double? Return4Tax4Tax { get; set; }
        public double? Dep1Total { get; set; }
        public double? Dep1Tax1Total { get; set; }
        public double? Dep1Tax1Tax { get; set; }
        public double? Dep1Tax2Total { get; set; }
        public double? Dep1Tax2Tax { get; set; }
        public double? Dep1Tax3Total { get; set; }
        public double? Dep1Tax3Tax { get; set; }
        public double? Dep1Tax4Total { get; set; }
        public double? Dep1Tax4Tax { get; set; }
        public double? Dep2Total { get; set; }
        public double? Dep2Tax1Total { get; set; }
        public double? Dep2Tax1Tax { get; set; }
        public double? Dep2Tax2Total { get; set; }
        public double? Dep2Tax2Tax { get; set; }
        public double? Dep2Tax3Total { get; set; }
        public double? Dep2Tax3Tax { get; set; }
        public double? Dep2Tax4Total { get; set; }
        public double? Dep2Tax4Tax { get; set; }
        public double? Dep3Total { get; set; }
        public double? Dep3Tax1Total { get; set; }
        public double? Dep3Tax1Tax { get; set; }
        public double? Dep3Tax2Total { get; set; }
        public double? Dep3Tax2Tax { get; set; }
        public double? Dep3Tax3Total { get; set; }
        public double? Dep3Tax3Tax { get; set; }
        public double? Dep3Tax4Total { get; set; }
        public double? Dep3Tax4Tax { get; set; }
        public double? Dep4Total { get; set; }
        public double? Dep4Tax1Total { get; set; }
        public double? Dep4Tax1Tax { get; set; }
        public double? Dep4Tax2Total { get; set; }
        public double? Dep4Tax2Tax { get; set; }
        public double? Dep4Tax3Total { get; set; }
        public double? Dep4Tax3Tax { get; set; }
        public double? Dep4Tax4Total { get; set; }
        public double? Dep4Tax4Tax { get; set; }
        public double? Dep5Total { get; set; }
        public double? Dep5Tax1Total { get; set; }
        public double? Dep5Tax1Tax { get; set; }
        public double? Dep5Tax2Total { get; set; }
        public double? Dep5Tax2Tax { get; set; }
        public double? Dep5Tax3Total { get; set; }
        public double? Dep5Tax3Tax { get; set; }
        public double? Dep5Tax4Total { get; set; }
        public double? Dep5Tax4Tax { get; set; }
        public double? Dep6Total { get; set; }
        public double? Dep6Tax1Total { get; set; }
        public double? Dep6Tax1Tax { get; set; }
        public double? Dep6Tax2Total { get; set; }
        public double? Dep6Tax2Tax { get; set; }
        public double? Dep6Tax3Total { get; set; }
        public double? Dep6Tax3Tax { get; set; }
        public double? Dep6Tax4Total { get; set; }
        public double? Dep6Tax4Tax { get; set; }
        public double? Dep7Total { get; set; }
        public double? Dep7Tax1Total { get; set; }
        public double? Dep7Tax1Tax { get; set; }
        public double? Dep7Tax2Total { get; set; }
        public double? Dep7Tax2Tax { get; set; }
        public double? Dep7Tax3Total { get; set; }
        public double? Dep7Tax3Tax { get; set; }
        public double? Dep7Tax4Total { get; set; }
        public double? Dep7Tax4Tax { get; set; }
        public double? Dep8Total { get; set; }
        public double? Dep8Tax1Total { get; set; }
        public double? Dep8Tax1Tax { get; set; }
        public double? Dep8Tax2Total { get; set; }
        public double? Dep8Tax2Tax { get; set; }
        public double? Dep8Tax3Total { get; set; }
        public double? Dep8Tax3Tax { get; set; }
        public double? Dep8Tax4Total { get; set; }
        public double? Dep8Tax4Tax { get; set; }
        public double? GlobalTotal1 { get; set; }
        public double? GlobalTotal2 { get; set; }
        public double? GlobalTotal3 { get; set; }
        public double? GlobalTotal4 { get; set; }
        public double? GlobalTotalReturn1 { get; set; }
        public double? GlobalTotalReturn2 { get; set; }
        public double? GlobalTotalReturn3 { get; set; }
        public double? GlobalTotalReturn4 { get; set; }
    }
}
